import type { FeatureId } from '@/constants/featureIds';

/**
 * ★ 功能项显示名（141 项），供「能力总览」页展示功能名列。
 *
 * ============ 为什么单独放一张表 ============
 * `constants/capabilities.ts` 的 `CAPABILITIES` 只有 id / level / reason / alternative / group，
 * **没有名称字段**；而名称属于展示层专有数据，硬塞进能力表会让 141 项常量再翻一倍、
 * 且牵动所有消费方。所以名称单独放这里，由 PRD §6（`docs/01-PRD-功能拆解.md`）逐项导出。
 *
 * ★ 边界（重要）：
 * - 本表**只提供名称**，不是能力数据的第二份真相；
 *   level / reason / alternative 一律以 `CAPABILITIES` 为准，**禁止**在这里补第二套判断；
 * - 与 `ModulePermissionPage` 的 `MODULE_CAPABILITIES`（15/17 项模块授权子集）无关，不要互相引用。
 *
 * ============ 生成方式 ============
 * 按 `ALL_FEATURE_IDS` 的稳定顺序从 PRD §6 表格逐行抽取，共 141 项，无遗漏。
 * 后续 PRD 改名时同步本表即可（缺失时 UI 回落到 id 本身，不会白屏）。
 */

/** 功能项显示名表 */
export const FEATURE_NAMES: Record<FeatureId, string> = {
  'PG-01': '聊天统计',
  'PG-02': '转发详情',
  'PG-03': '聊天搜索',
  'PG-04': '音色试听',
  'PG-05': '语音通话',
  'PG-06': '图片预览',
  'PG-07': '引导',
  'PG-08': '收藏',
  'PG-09': '聊天设置',
  'PG-10': '上下文设置',
  'PG-11': '总结范围选择',
  'PG-12': '记忆库管理',
  'PG-13': '记忆编辑',
  'PG-14': '首页 v1',
  'PG-15': '首页 v2',
  'PG-16': '主聊天',
  'PG-17': '全局设置',
  'PG-18': '连接测试',
  'PG-19': '开发者',
  'PG-20': '诊断',
  'PG-21': '赞助',
  'PG-22': '全屏文本',
  'PG-23': '外部接入设置',
  'PG-24': '模块 WebView',
  'PG-25': '模块权限',
  'PG-26': '第三方 SDK 公示',
  'PG-27': '崩溃页',
  'SV-01': '音乐悬浮窗服务',
  'SV-02': 'ILink 服务',
  'SV-03': '外部接入服务',
  'SV-04': '桌宠陪伴服务',
  'SV-05': '桌面无障碍服务',
  'SV-06': '主动消息服务',
  'SV-07': '主动消息接收器',
  'SV-08': '自动备份服务',
  'SV-09': '外部接入保活接收器',
  'SV-10': '外部接入开机接收器',
  'SV-11': '开机完成接收器',
  'FN-01': '聊天统计',
  'FN-02': '一键导入',
  'FN-03': '一键导出',
  'FN-04': '上下文清洗',
  'FN-05': '上下文设置',
  'FN-06': '主动消息',
  'FN-07': '主动消息继承',
  'FN-08': '主动消息间隔',
  'FN-09': '停用超时',
  'FN-10': '全天候主动消息',
  'FN-11': '兼容模式',
  'FN-12': '内容过滤',
  'FN-13': '加载范围',
  'FN-14': '动态主动性',
  'FN-15': '单次最大条数',
  'FN-16': '双击返回键退出',
  'FN-17': '发送延时',
  'FN-18': '后台消息',
  'FN-19': '后台消息Toast',
  'FN-20': '后台消息退出确认',
  'FN-21': '启用Markdown',
  'FN-22': '回车发送',
  'FN-23': '图片视频立即发送',
  'FN-24': '多条消息延时',
  'FN-25': '多模态兼容模式',
  'FN-26': '导出日志',
  'FN-27': '拍一拍后缀',
  'FN-28': '提供完整记忆库',
  'FN-29': '提供范围记忆',
  'FN-30': '提示词注入控制',
  'FN-31': '提示词约束',
  'FN-32': '收藏',
  'FN-33': '文生图二次确认',
  'FN-34': '时间感知',
  'FN-35': '更新说明',
  'FN-36': '最大条数限制',
  'FN-37': '桌宠模式',
  'FN-38': '深色模式',
  'FN-39': '清除立绘',
  'FN-40': '灰色化',
  'FN-41': '生命',
  'FN-42': '病娇模式',
  'FN-43': '窗口最小化',
  'FN-44': '聊天记录合并',
  'FN-45': '联网搜索',
  'FN-46': '自动分割',
  'FN-47': '自动备份',
  'FN-48': '自动总结',
  'FN-49': '自定义参数',
  'FN-50': '角色文生图设置',
  'FN-51': '角色模型',
  'FN-52': '角色立绘',
  'FN-53': '角色立绘Live2D',
  'FN-54': '角色立绘桌宠',
  'FN-55': '角色音色',
  'FN-56': '记忆库',
  'FN-57': '记忆搜索得分',
  'FN-58': '诊断',
  'FN-59': '语音功能',
  'FN-60': '输入状态',
  'FN-61': '重置主题',
  'FN-62': '高级配置',
  'FN-63': '多选',
  'PL-01': 'INTERNET',
  'PL-02': 'RECORD_AUDIO',
  'PL-03': 'CAMERA',
  'PL-04': 'BLUETOOTH_CONNECT',
  'PL-05': 'SYSTEM_ALERT_WINDOW',
  'PL-06': 'BIND_ACCESSIBILITY_SERVICE',
  'PL-07': 'DEVICE_ADMIN',
  'PL-08': 'RECEIVE_BOOT_COMPLETED',
  'PL-09': 'SCHEDULE_EXACT_ALARM',
  'PL-10': 'FOREGROUND_SERVICE',
  'PL-11': 'MANAGE_EXTERNAL_STORAGE',
  'PL-12': 'VIBRATE',
  'PL-13': 'POST_NOTIFICATIONS',
  'PL-14': 'libsherpa-onnx（端侧 TTS/ASR）',
  'PL-15': 'libonnxruntime（端侧推理）',
  'PL-16': 'libquickjs-android-wrapper（JS 引擎）',
  'PL-17': 'libpl_droidsonroids_gif（GIF）',
  'PL-18': 'ML Kit OCR',
  'PL-19': 'journeyapps barcodescanner',
  'PL-20': 'Firebase datatransport',
  'PL-21': '<外部加固壳>（加固壳）',
  'EX-01': '5 步向导 UI',
  'EX-02': '原材料 A：微信聊天记录',
  'EX-03': '原材料 B：iMessage / 短信',
  'EX-04': '原材料 C：照片 EXIF 时间线',
  'EX-05': '原材料 D：社交媒体导出',
  'EX-06': '原材料 E：上传文件',
  'EX-07': '原材料 F：直接粘贴',
  'EX-08': '双线分析 + 生成（Memories / Persona 6 层）',
  'EX-09': '产物写入 + 版本管理/回滚',
  'EX-10': '对话纠正（Correction 记录）',
  'XR-01': '系统提示词装配（欣然 5 层）',
  'XR-02': 'UI 文案 / 空状态 / 错误提示人格化',
  'XR-03': '主动消息人格化',
  'XR-04': '欢迎语（first_mes / alternate_greetings）',
  'XR-05': '昵称与自称约束',
  'XR-06': '隐私红线（禁图像生成）',
  'XR-07': '欣然角色卡预置',
  'XR-08': '与蒸馏产物共存（多角色切换）',
  'XR-09': '语音 / 表情包人格一致性',
} as const;

/** 取功能项显示名（未收录时回落为 id 本身，保证 UI 永不空白） */
export function featureName(id: FeatureId): string {
  return FEATURE_NAMES[id] ?? id;
}

export default FEATURE_NAMES;
