/**
 * ★ 文案 key 联合类型（架构文档 §6.8 第一道防线）。
 *
 * `COPY_KEYS` 是唯一真源，`CopyKey` 由其推导：
 * - `src/copy/xinran.ts` 声明为 `Record<CopyKey, string>`，**少一个 key 直接编译报错**；
 * - 组件里只能用 `t(key)` / `useCopy()`，禁止出现面向用户的中文字符串字面量；
 * - `scripts/check-copy.ts` 会扫描 `src/features/**` 与 `src/components/**` 做 CI 兜底。
 *
 * 命名约定：`<域>.<语义>`，域 = common / nav / app / empty / loading / ok / err /
 * confirm / settings / gate / crash / tip / action / alt。
 */
export const COPY_KEYS = [
  // —— 通用动作 ——
  'common.confirm',
  'common.cancel',
  'common.save',
  'common.delete',
  'common.edit',
  'common.close',
  'common.back',
  'common.retry',
  'common.copy',
  'common.copied',
  'common.search',
  'common.add',
  'common.import',
  'common.export',
  'common.on',
  'common.off',
  'common.reset',
  'common.clear',
  'common.more',
  'common.selectAll',
  'common.deselectAll',
  'common.open',
  'common.preview',
  'common.download',
  'common.upload',
  'common.refresh',
  'common.next',
  'common.prev',
  'common.done',
  'common.enabled',
  'common.disabled',
  'common.yes',
  'common.no',

  // —— 导航与标题 ——
  'nav.home',
  'nav.chat',
  'nav.memories',
  'nav.favorites',
  'nav.distill',
  'nav.settings',
  'nav.about',
  'nav.moments',
  // ★ 反馈信箱（2026-10-04）：不是底部 Tab 的一级入口，只是 `/settings/feedback`
  //   这个子页的 TopBar 标题。落主表是因为 `resolveTitleKey()` 的返回值类型是 `CopyKey`，
  //   域内表（`feedbackCopy.ts`）的 key 传不进去 —— 同 `nav.moments` 的理由。
  'nav.feedback',
  'app.title',
  'app.subtitle',
  'app.booting',

  // —— 空状态 ——
  'empty.sessions',
  'empty.messages',
  'empty.memories',
  'empty.favorites',
  'empty.search',
  'empty.personas',
  // 不内置版（standalone）：无任何角色时的空态，**不能沿用 `empty.personas`**
  // ——那句是「只有我一个」，以"欣然已存在"为前提（见 buildMode.ts）
  'empty.personasSolo',
  // 不内置版首页「无角色」引导块（替代 PersonaRail 的位置）
  'empty.noPersona',
  'empty.stickers',
  'empty.distillJobs',
  'empty.logs',
  'empty.backups',
  'empty.timbres',
  'empty.live2d',
  'empty.selection',

  // —— 加载/等待 ——
  'loading.default',
  'loading.thinking',
  'loading.streaming',
  'loading.summarizing',
  'loading.distilling',
  'loading.importing',
  'loading.exporting',
  'loading.ocr',
  'loading.connectTest',
  'loading.restoring',

  // —— 成功反馈 ——
  'ok.saved',
  'ok.imported',
  'ok.exported',
  'ok.memorySaved',
  'ok.backupDone',
  'ok.distillDone',
  'ok.deleted',
  'ok.themeReset',
  'ok.portraitCleared',
  'ok.favorited',
  'ok.unfavorited',
  // ★ 世界设定导入成功（2026-10-04）
  'ok.worldImported',
  'ok.forwarded',
  'ok.merged',
  'ok.rollback',
  'ok.logsExported',
  'ok.connectionOk',
  // ★ 反馈相关提示（2026-10-04）。为什么这**四条提示**落主表而表单/信箱文案落
  //   `feedbackCopy.ts` 域内表：
  //   ① `useSnack` 的入参类型是 `CopyKey`，**域内表的 key 传不进去**
  //      （同 `ok.worldImported` / `ok.memorySaved` 的处境）；
  //   ② 「保存 / 导出 / 删除成功」这三句直接复用主表已有的 `ok.saved` /
  //      `ok.exported` / `ok.deleted`，不新造 —— 新造只会让同一句话有两个来源。
  //   只新增"主表里确实没有对应说法"的四条：提交成功、备注保存、复制失败、分享失败。
  'ok.feedbackSaved',
  'ok.feedbackNoteSaved',
  'err.feedbackCopyFailed',
  'err.feedbackShareFailed',

  // —— 错误（★ 必须承担责任，不甩锅） ——
  'err.llmFailed',
  'err.llmTimeout',
  'err.llmAuth',
  'err.llmAbort',
  'err.llmNoProvider',
  'err.llmNoModel',
  'err.parseFail',
  'err.parseUnsupported',
  'err.dbFailed',
  // 无角色时试图新建会话（不内置版首启会走到）
  'err.noPersonaToChat',
  'err.privacyBlock',
  'err.capabilityUnavailable',
  'err.importInvalid',
  // 导入校验的细分原因（persona importer 抛错，但会渲染进导入报告的 DOM，属用户面向）
  'err.importNotJson',
  'err.importNoCard',
  'err.importEmpty',
  'err.importNoFile',
  'err.importTooMany',
  'err.importTooLarge',
  'err.importBadExt',
  // ★ PNG 载体角色卡暂不支持：不再走「格式不认得」的通用文案，
  //   而是明确告诉用户「PNG 里嵌的卡我读不了」+ 给替代办法（导出 .json / .zip）。
  'err.importPngCard',
  // ★ 表情包条目一条都没解析出来时报的可见原因（丢弃必须可见，不能静默 continue）
  'err.importStickerSkipped',
  'err.networkOffline',
  'err.ocrFailed',
  'err.ttsFailed',
  'err.asrFailed',
  'err.storageFull',
  'err.microphoneDenied',
  'err.notificationDenied',
  // ★ 世界设定导入：识别到的东西很少时提示用户（不是"失败"，是"没读懂多少"）
  'err.worldNotRecognized',
  'err.unknown',

  // —— 二次确认 ——
  'confirm.deleteSession',
  'confirm.deleteMessage',
  'confirm.deletePersona',
  'confirm.deleteMemory',
  'confirm.resetTheme',
  'confirm.exitApp',
  'confirm.imageGen',
  'confirm.distillCost',
  'confirm.clearLogs',
  'confirm.rollback',
  'confirm.deleteCorrection',
  'confirm.deleteDistill',
  'confirm.clearPortrait',
  'confirm.deleteBackup',
  'confirm.deleteMoment',
  'confirm.deleteStickerPack',
  // ★ 反馈的两条二次确认（2026-10-04）。落主表而非 `feedbackCopy.ts`：
  //   `ConfirmDialog` 的 `titleKey` 只收 `CopyKey`（同 `confirm.deleteMoment` 的理由）。
  //   ★ 为什么不复用 `confirm.clearLogs`：那句说的是"日志"，
  //     而这里删的是**用户自己写的反馈**，代价完全不同 —— 张冠李戴的确认框
  //     会让用户在读错标题的情况下点掉自己的东西。
  'confirm.deleteFeedback',
  'confirm.clearFeedback',

  // —— 设置分组与说明 ——
  'settings.group.model',
  'settings.group.chat',
  'settings.group.context',
  'settings.group.proactive',
  'settings.group.appearance',
  'settings.group.voice',
  'settings.group.memory',
  'settings.group.backup',
  'settings.group.advanced',
  'settings.group.about',
  'settings.group.ilink',
  // ★ 世界设定（2026-10-04）：内置版显示内置世界、不内置版是导入窗口
  'settings.group.world',
  'settings.group.shortcuts',
  'settings.group.stickers',
  'settings.group.moments',
  // ★ 反馈与建议分组标题（2026-10-04）。必须是**主表** key：
  //   `SettingsPage` 的 `titleKey` 收的是 `CopyKey`，域内表的 key 进不去
  //   （同 `settings.group.shortcuts` 的理由）。
  'settings.group.feedback',
  'settings.hint.baseUrl',
  'settings.hint.apiKey',
  'settings.hint.model',
  'settings.hint.compatMode',
  'settings.hint.multimodalCompat',
  'settings.hint.timeout',
  'settings.hint.contextCount',
  'settings.hint.maxMessages',
  'settings.hint.loadRange',
  'settings.hint.contextClean',
  'settings.hint.injectControl',
  'settings.hint.promptConstraints',
  'settings.hint.timeAware',
  'settings.hint.memoryScope',
  'settings.hint.memoryThreshold',
  // 记忆检索范围的三档名称（PG-10 上下文设置的下拉项）
  'settings.scope.session',
  'settings.scope.global',
  'settings.scope.range',
  // 上下文清洗四个子项（PG-10）
  'settings.clean.removeEmpty',
  'settings.clean.dedupe',
  'settings.clean.trimSystem',
  'settings.clean.mergeConsecutive',
  // 提示词注入四个子项（PG-10 / FN-30）
  'settings.inject.system',
  'settings.inject.worldBook',
  'settings.inject.memory',
  'settings.inject.jailbreak',
  // 记忆：全量注入（阈值压到 0，仍受预算约束）
  'settings.memory.full',
  'settings.hint.proactiveInterval',
  'settings.hint.idleTimeout',
  'settings.hint.allDay',
  'settings.hint.dynamic',
  'settings.hint.sendDelay',
  'settings.hint.multiDelay',
  'settings.hint.autoSplit',
  'settings.hint.contentFilter',
  'settings.hint.patSuffix',
  'settings.hint.typingIndicator',
  'settings.hint.markdown',
  'settings.hint.enterToSend',
  'settings.hint.mediaImmediate',
  'settings.hint.autoSummary',
  'settings.hint.autoBackup',
  'settings.hint.webSearch',
  'settings.hint.params',
  'settings.hint.darkMode',
  'settings.hint.grayscale',
  'settings.hint.yandere',
  'settings.hint.petMode',
  'settings.hint.petLife',
  'settings.hint.windowMinimized',
  'settings.hint.homeLayout',
  'settings.hint.resetTheme',
  'settings.hint.advanced',
  'settings.hint.bridge',
  'settings.hint.dev',

  // —— 能力闸门 ——
  'gate.unavailable',
  'gate.partial',
  'gate.reasonPrefix',
  'gate.altPrefix',

  // —— 崩溃页 ——
  'crash.title',
  'crash.desc',
  'crash.copyLogs',
  'crash.reload',
  'crash.safeMode',

  // —— 其它提示 ——
  'tip.privacyNoImage',
  'tip.providerMissing',
  'tip.guideDone',
  'tip.petPaused',
  'tip.backgroundResume',
  'tip.storageWarning',
  'tip.updateNotes',
  // 多标签页单写者：非主标签页只读提示（决策 A9）
  'tip.readOnlyTab',
  'action.newSession',
  // 导入人设文件（不内置版无角色时的主行动）
  'action.importPersona',
  'action.newMemory',
  'action.newDistill',
  'action.archive',
  // —— 会话 ——
  'session.titleField',
  'session.unnamed',
  // —— 首页 ——
  'home.sessionTitle',
  // 首页快捷入口（**历史遗留，当前 0 个消费点**）
  //   原属 `features/home/QuickEntries.tsx`；该组件 2026-10-04 迁到设置页
  //   （`features/settings/sections/ShortcutsSection.tsx`）并改用了
  //   `nav.*` / `settings.group.*` 既有 key。这 4 条在那之前就已无消费点，
  //   保留是为了不改动条数与历史；**新代码不要再引用**。
  'home.quickNewChat',
  'home.quickDistill',
  'home.quickImport',
  'home.quickSettings',
  // —— 引导 4 步标题（PG-07）——
  'guide.step1',
  'guide.step2',
  // 不内置版第 2 步标题：原「认识一下我」是欣然第一人称，此时没有"我"
  'guide.step2Solo',
  'guide.step3',
  'guide.step4',
  'pat.message',

  // —— 聊天域（T08：主闭环 + 统计 / 搜索 / 设置 / 上下文 / 转发 / 收藏 / 预览） ——
  'chat.title',
  'chat.send',
  'chat.stop',
  'chat.placeholder',
  'chat.retry',
  'chat.regenerate',
  'chat.copy',
  'chat.favorite',
  'chat.unfavorite',
  'chat.forward',
  'chat.merge',
  'chat.pat',
  'chat.select',
  'chat.exitSelect',
  'chat.selectedCount',
  'chat.stats',
  'chat.searchInChat',
  'chat.settings',
  'chat.context',
  'chat.sticker',
  'chat.camera',
  'chat.cameraStarting',
  'chat.cameraShutter',
  'chat.cameraFlip',
  'chat.cameraRetake',
  'chat.cameraUse',
  'chat.cameraShotReady',
  'chat.cameraRetry',
  'chat.cameraErrDenied',
  'chat.cameraErrNoDevice',
  'chat.cameraErrInUse',
  'chat.cameraErrInsecure',
  'chat.cameraErrUnsupported',
  'chat.cameraErrFailed',
  'chat.cameraTooLarge',
  'chat.image',
  'chat.attachImage',
  'chat.jump',
  'chat.forwardFrom',
  'chat.forwardedCount',
  'chat.mergedCount',
  'chat.statsTitle',
  'chat.statsMessages',
  'chat.statsChars',
  'chat.statsTokens',
  'chat.statsActive',
  'chat.statsDays',
  'chat.statsRange',
  'chat.textTitle',
  'chat.readerFont',
  'chat.favTitle',
  'chat.previewTitle',
  'chat.ocr',
  'chat.ocrHint',
  'chat.ocrFallback',
  'chat.zoomReset',
  'chat.searchEmpty',
  'chat.noMore',
  'chat.proactiveTag',
  'chat.nicknameWarn',
  'chat.contextTitle',
  'chat.promptTitle',
  'chat.tokenBudget',
  'chat.typing',
  'chat.summarizing',
  // 搜索命中数（PG-03）与转发溯源（PG-02）
  'chat.hitCount',
  'chat.originSession',
  'chat.targetSessions',
  // 气泡长按菜单「存成记忆」（T10 聊天内就地记忆入口，见 usePersonaMemoryEntry）
  'chat.saveAsMemory',

  // —— 通用组件里的界面词（组件内禁止写中文字面量） ——
  'ui.promptPreview',
  'ui.copyPrompt',
  'ui.expand',
  'ui.segmentEmpty',
  'ui.segmentInjected',
  'ui.segmentNotInjected',
  'ui.segmentTruncated',
  'ui.tokenOverBudget',
  // 导入表情包时的默认包名模板（会渲染到表情包面板，属用户面向）
  'ui.stickerPackName',
  // TokenBadge 的 token 估算 Tooltip（未设预算 / 设了预算两种文案）
  'ui.tokenEstimateTip',
  'ui.tokenBudgetTip',
  'ui.dropHere',
  'ui.pickFiles',
  'ui.pickFilesMulti',
  'ui.pickFolder',
  'ui.dirUnsupported',
  'ui.noMatchedFile',
  'ui.materialFiles',
  'ui.live2dLoaded',
  'ui.live2dFailed',
  'ui.renderError',
  'ui.shellReady',

  // —— 能力降级替代方案文案 ——
  'alt.notNeeded',
  'alt.noEquivalent',
  'alt.notApplicable',
  'alt.floatingWindow',
  'alt.manualImport',
  'alt.heartbeat',
  'alt.broadcastChannel',
  'alt.notificationToast',
  'alt.exitConfirm',
  'alt.backgroundWorker',
  'alt.truncateMemory',
  'alt.yandereSeasoning',
  'alt.layoutCollapse',
  'alt.corsProxy',
  'alt.imageGenOptional',
  'alt.imageGenPersonaHidden',
  'alt.webSpeech',
  'alt.bm25Score',
  'alt.webProbe',
  'alt.customHeaderOnly',
  'alt.tsRewrite',
  'alt.exportOnly',
  'alt.manualExportSms',
  'alt.manualPickFolder',
  'alt.genericTextFallback',
  'alt.ocrOrDescribe',
  'alt.onnxOptional',
  'alt.workerSandbox',
  'alt.tesseract',
  'alt.localLog',
  'alt.visualFeedback',
  'alt.pwaInstall',
  'alt.singleFilePicker',
  'alt.realtimeThreeStage',
  'alt.staticSponsor',
  'alt.iframeSandbox',
  'alt.browserPermission',
  'alt.layoutToggle',
  'alt.ttsFallback',
  'alt.proactiveHidden',
  'alt.stickerAndCopy',
  'alt.proactiveNight',
  'alt.dynamicProactive',
  'alt.gpuPerformance',
  'alt.restoreOnStart',

  // —— 语音通话页（PG-04 / PG-05）文案 ——
  // ★ 为什么放主表而不新建「语音域内表」：语音页是**跨设置域的独立页面**
  //   （路由 /voice/call，首页快捷入口直达），不是设置页里的一个分区；
  //   settingsCopy 的 `voice.*` 是「设置里配语音」的文案，两者前缀相同但语义不同层，
  //   再开一张域内表等于给同一前缀造第三份真相。主表是跨域 UI 文案的唯一真源，放这里。
  'voice.pipelineTitle',
  'voice.stage.listening',
  'voice.stage.thinking',
  'voice.stage.speaking',
  'voice.panel.asr',
  'voice.panel.reply',
  'voice.channel.asr',
  'voice.channel.tts',
  'voice.input.manual',
  'voice.action.start',
  'voice.action.stop',
  'voice.action.send',
  // ★ `voice.asrOffHint`（A3′ 第 2 项，2026-10-04）：麦克风按钮置灰时 Tooltip 里的说明。
  //   落主表的理由与上面这一组相同（`/voice/call` 是跨设置域的独立页面，不是设置页里的分区）。
  //   ★ 判据自查：「不许断言会过期的状态」④ **不成立**——本条**只在 `voice.enabled && voice.asr` 为假时渲染**，
  //     「现在关着」由当次渲染实时求值，永远是当下的真话；与 20+ 条 `empty.*` 同一理由，
  //     故**不挂回改标记**。（② 未来指向：无。① 控制权：无。③ 范围外推：无。）
  'voice.asrOffHint',

  // —— 语音试听页（/voice/test，设置 → 语音 → 去试听）文案 ——
  // ★★ 这一组是**纠正一次误判**后补的：本页原先被我自己标成 `@copy-tier B`（开发者面向、
  //   允许技术标签），理由是「只剩设置 → 语音这一条开发者通路」。这个理由是错的——
  //   设置 → 语音 → 去试听是**一级用户路径**（`VoiceSection.tsx:114`，按钮文案 `voice.goTest`），
  //   不是开发者通路。判据一直都是「谁会看到它」，而用户看得到。故本页降回 A 档，
  //   原先裸露的 `sherpaWasm` / `cloud` / `webSpeech` 与三句英文说明全部收编到下面这些 key。
  'voice.channel.sherpaWasm',
  'voice.channel.cloud',
  'voice.channel.webSpeech',
  'voice.channelNote.sherpaWasm',
  'voice.channelNote.cloud',
  'voice.channelNote.webSpeech',
  'voice.channelStatus',
  'voice.lastUsed',
  'voice.field.sherpaModel',
  'voice.field.testText',
  'voice.hint.sherpaNotDeployed',

  // —— 音色管理（TimbreManager，挂在语音试听页里）文案 ——
  // ★ 同属那次误判的连带修正：它随 VoiceTestPage 一起进了用户视野，
  //   B 档豁免不成立。`voice.timbre.voiceIdHelper` 保留了原文那句如实披露
  //   （固定音色编号 ≠ 声音克隆），只是换成中文——豁免的是"要不要走文案表"，
  //   不是"能不能不如实说"。
  'voice.timbre.provider',
  'voice.timbre.provider.webSpeech',
  'voice.timbre.provider.siliconflow',
  'voice.timbre.provider.custom',
  'voice.timbre.providerHint.webSpeech',
  'voice.timbre.providerHint.siliconflow',
  'voice.timbre.providerHint.custom',
  'voice.timbre.option',
  'voice.timbre.field.voiceId',
  'voice.timbre.voiceIdHelper',
  'voice.timbre.field.sampleText',
  'voice.timbre.field.name',
  'voice.timbre.field.refMp3',

  // —— 模型商预设提示（src/constants/providers.ts）——
  // ★★ 落主表、不落 settingsCopy 域内表，理由比「避免反向依赖」更硬：
  //    `providers.ts` 在 `src/constants/`（共享常量层），实际消费者有四个——
  //    `db/bootstrap.ts`、`llm/adapter/multimodal.ts`、`llm/webSearch.ts`、`features/settings/ModelSection.tsx`。
  //    若文案落 `features/settings/settingsCopy.ts`，则 `db`/`llm` 两层为了取文案就得 import `@/features/**`，
  //    **直接违反「db / llm / store / persona 零 features 引用」的分层约束**。主表（`@/copy`）零新增依赖。
  'provider.note.siliconflow',
  'provider.note.custom',

  // —— 顶栏两个 aria-label（src/layouts/TopBar.tsx）——
  // ★ 为什么必须入表：`aria-label` 不显示在界面上，但**会被读屏念出来**。
  //   按 §6.5.3 的 a11y 判据（「会不会到用户耳朵里」）它就是 A 档。
  //   `menu` / `toggle-theme` 是可翻的词，不是技术标识符，所以不能按第三类豁免处理。
  // ★ 不复用 settingsCopy 的 `label.darkMode`：那是**域内表**，`layouts/` 是共享布局层，
  //   共享层引用 features 域内表会形成反向依赖（§6.5.2 分层约束）。
  'ui.aria.menu',
  'ui.aria.toggleTheme',

  // —— token 估算徽标（src/components/TokenBadge）——
  // ★ 这条是 A 档判据改成「按取值方式，不看字符种类」之后才浮出来的：
  //    ` tok` 是英文，改造前的 CJK 扫描完全看不见它。
  'ui.tokenBadge',

  // —— 模块网页页（PG-24）文案 ——
  'ui.moduleUrl',
  'ui.moduleFrame',
  /* ——————————————— 能力表 141 项的原因与补充说明（cap.*） ——————————————— */
  // ★ 2026-10-04 归口（software-engineer-5）：原先是 `capabilities.ts` 里的中文字面量，
  //   在能力总览页 / CapabilityGate / 模块权限页**原样渲染给用户** ⇒ 按 §6.5.3 是 A 档。
  //   ★★ 消费点必须包 `t()`（7 处，清单见 docs/07 §6.5.6）：
  //      `CopyKey` 是 string 的子集，漏包**编译照过**，只会显示成 raw key——
  //      这是「第五种假绿」，tsc / lint:copy / lint:copyTables / vite build 四条全绿。
  'cap.reason.PG-01',
  'cap.reason.PG-02',
  'cap.reason.PG-03',
  'cap.reason.PG-04',
  'cap.note.PG-04',
  'cap.reason.PG-05',
  'cap.note.PG-05',
  'cap.reason.PG-06',
  'cap.reason.PG-07',
  'cap.reason.PG-08',
  'cap.reason.PG-09',
  'cap.reason.PG-10',
  'cap.reason.PG-11',
  'cap.reason.PG-12',
  'cap.reason.PG-13',
  'cap.reason.PG-14',
  'cap.reason.PG-15',
  'cap.reason.PG-16',
  'cap.reason.PG-17',
  'cap.reason.PG-18',
  'cap.reason.PG-19',
  'cap.reason.PG-20',
  'cap.reason.PG-21',
  'cap.reason.PG-22',
  'cap.reason.PG-23',
  'cap.note.PG-23',
  'cap.reason.PG-24',
  'cap.reason.PG-25',
  'cap.reason.PG-26',
  'cap.reason.PG-27',
  'cap.reason.SV-01',
  'cap.note.SV-01',
  'cap.reason.SV-02',
  'cap.reason.SV-03',
  'cap.reason.SV-04',
  'cap.note.SV-04',
  'cap.reason.SV-05',
  'cap.note.SV-05',
  'cap.reason.SV-06',
  'cap.note.SV-06',
  'cap.reason.SV-07',
  'cap.reason.SV-08',
  'cap.reason.SV-09',
  'cap.reason.SV-10',
  'cap.reason.SV-11',
  'cap.reason.FN-01',
  'cap.reason.FN-02',
  'cap.note.FN-02',
  'cap.reason.FN-03',
  'cap.reason.FN-04',
  'cap.reason.FN-05',
  'cap.reason.FN-06',
  'cap.note.FN-06',
  'cap.reason.FN-07',
  'cap.reason.FN-08',
  'cap.reason.FN-09',
  'cap.reason.FN-10',
  'cap.reason.FN-11',
  'cap.reason.FN-12',
  'cap.reason.FN-13',
  'cap.reason.FN-14',
  'cap.reason.FN-15',
  'cap.reason.FN-16',
  'cap.note.FN-16',
  'cap.reason.FN-17',
  'cap.reason.FN-18',
  'cap.reason.FN-19',
  'cap.reason.FN-20',
  'cap.reason.FN-21',
  'cap.reason.FN-22',
  'cap.reason.FN-23',
  'cap.reason.FN-24',
  'cap.reason.FN-25',
  'cap.reason.FN-26',
  'cap.reason.FN-27',
  'cap.reason.FN-28',
  'cap.reason.FN-29',
  'cap.reason.FN-30',
  'cap.reason.FN-31',
  'cap.reason.FN-32',
  'cap.reason.FN-33',
  'cap.reason.FN-34',
  'cap.reason.FN-35',
  'cap.reason.FN-36',
  'cap.reason.FN-37',
  'cap.reason.FN-38',
  'cap.reason.FN-39',
  'cap.reason.FN-40',
  'cap.reason.FN-41',
  'cap.reason.FN-42',
  'cap.note.FN-42',
  'cap.reason.FN-43',
  'cap.reason.FN-44',
  'cap.reason.FN-45',
  'cap.reason.FN-46',
  'cap.reason.FN-47',
  'cap.reason.FN-48',
  'cap.reason.FN-49',
  'cap.reason.FN-50',
  'cap.note.FN-50',
  'cap.reason.FN-51',
  'cap.reason.FN-52',
  'cap.reason.FN-53',
  'cap.note.FN-53',
  'cap.reason.FN-54',
  'cap.reason.FN-55',
  'cap.note.FN-55',
  'cap.reason.FN-56',
  'cap.reason.FN-57',
  'cap.reason.FN-58',
  'cap.reason.FN-59',
  'cap.note.FN-59',
  'cap.reason.FN-60',
  'cap.reason.FN-61',
  'cap.reason.FN-62',
  'cap.reason.FN-63',
  'cap.reason.PL-01',
  'cap.reason.PL-02',
  'cap.reason.PL-03',
  'cap.reason.PL-04',
  'cap.reason.PL-05',
  'cap.reason.PL-06',
  'cap.reason.PL-07',
  'cap.reason.PL-08',
  'cap.reason.PL-09',
  'cap.reason.PL-10',
  'cap.reason.PL-11',
  'cap.reason.PL-12',
  'cap.reason.PL-13',
  'cap.note.PL-13',
  'cap.reason.PL-14',
  'cap.note.PL-14',
  'cap.reason.PL-15',
  'cap.reason.PL-16',
  'cap.reason.PL-17',
  'cap.reason.PL-18',
  'cap.reason.PL-19',
  'cap.reason.PL-20',
  'cap.reason.PL-21',
  'cap.reason.EX-01',
  'cap.reason.EX-02',
  'cap.reason.EX-03',
  'cap.note.EX-03',
  'cap.reason.EX-04',
  'cap.note.EX-04',
  'cap.reason.EX-05',
  'cap.reason.EX-06',
  'cap.reason.EX-07',
  'cap.reason.EX-08',
  'cap.note.EX-08',
  'cap.reason.EX-09',
  'cap.reason.EX-10',
  'cap.reason.XR-01',
  'cap.reason.XR-02',
  'cap.reason.XR-03',
  'cap.reason.XR-04',
  'cap.reason.XR-05',
  'cap.reason.XR-06',
  'cap.reason.XR-07',
  'cap.reason.XR-08',
  'cap.reason.XR-09',
  'cap.reason.full',

  // ——————————————— 微信 ClawBot（iLink Bot 通道，`ilink.*`） ———————————————
  // ★ 为什么另起一段而不是塞进 `settings.*`：这些 key 的消费者不止设置页——
  //   登录状态机（`src/ilink/login.ts`）直接返回 `CopyKey` 作为状态/失败原因，
  //   收消息循环也会往 UI 回状态。把它们挂 `settings.*` 会让「设置文案」被迫服务非设置场景。
  'ilink.label.enabled',
  'ilink.label.receive',
  'ilink.label.inherit',
  'ilink.label.voice',
  'ilink.label.verifyCode',
  'ilink.label.qrcodeId',
  'ilink.action.bind',
  'ilink.action.save',
  'ilink.action.test',
  'ilink.action.unbind',
  'ilink.action.submitCode',
  'ilink.action.retry',
  'ilink.note.foregroundOnly',
  'ilink.note.nonNative',
  'ilink.note.mediaUnavailable',
  'ilink.note.tokenPlaintext',
  'ilink.note.unbindLocalOnly',
  'ilink.note.voiceNotImplemented',
  'ilink.state.idle',
  'ilink.state.fetchingQr',
  'ilink.state.scanQr',
  'ilink.state.scanned',
  'ilink.state.needVerifyCode',
  'ilink.state.verifySubmitted',
  'ilink.state.redirected',
  'ilink.state.refreshingQr',
  'ilink.state.bound',
  'ilink.state.reuseLocalCredentials',
  'ilink.state.stopped',
  'ilink.err.missingCredentials',
  'ilink.err.boundElsewhere',
  'ilink.err.qrRefreshLimit',
  'ilink.err.network',
  'ilink.err.http',
  'ilink.err.protocol',
  'ilink.err.notNative',
  'ilink.err.qrRenderFailed',
  'ilink.toast.saved',
  'ilink.toast.bound',
  'ilink.toast.unbound',
  'ilink.toast.testSent',
  'ilink.toast.testFailed',
  'ilink.inbound.image',
  'ilink.inbound.voice',
  'ilink.inbound.unsupported',
  'ilink.session.title',
  'ilink.test.message',

] as const;

/** 文案 key 联合类型 */
export type CopyKey = (typeof COPY_KEYS)[number];

/** 文案变量（占位符 `{name}` 会被替换） */
export type CopyVars = Record<string, string | number>;
