#!/usr/bin/env node
/**
 * 双版本 APK 打包（内置欣然 / 不内置欣然）。
 *
 * ★ 为什么要有这个脚本，而不是在文档里写三条命令：
 *   两个包的差别**只在构建期环境变量 `VITE_BUILTIN_XINRAN`**，而它同时影响两处：
 *     ① `vite build` 产出的 `dist/`（web 层：种不种欣然卡）
 *     ② `cap sync` 产出的 `android/app/src/main/assets/capacitor.config.json`（原生层：appId/appName）
 *   这两处**必须成对切换**。手工执行时极易出现"原生是 standalone 名、web 却内置了欣然"
 *   这种半吊子组合，而且**打出来的包表面上看不出问题**——只有装上去才发现首启多了个角色。
 *   ⇒ 把配对关系固化进脚本，用一次调用完成"切 web → 同步原生 → 编译"。
 *
 * ★ 双保险：脚本会**直接检查打进 APK 的 assets**，用种子分支里的独特字符串确认版本正确
 *   （判据见 `src/constants/buildMode.ts` 头部注释——注意**不能用 `grep 欣然`**，
 *    文案表两版都在，那样区分不了）。
 *
 * 用法：
 *   node scripts/build-apk.mjs            # 两个版本都打
 *   node scripts/build-apk.mjs builtin    # 只打内置版
 *   node scripts/build-apk.mjs standalone # 只打不内置版
 *
 * 前置：
 *   - `android/local.properties` 指向本机 Android SDK
 *   - `JAVA_HOME` 指向 JDK 17+（Capacitor 7 / AGP 8 要求）
 *   - `android/keystore.properties` + keystore 文件（缺失则出 unsigned 包，装不上）
 */
import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  copyFileSync,
  appendFileSync,
  renameSync,
  writeFileSync,
  openSync,
  readSync,
  closeSync,
  fstatSync,
} from 'node:fs';
import { inflateRawSync } from 'node:zlib';
import { join, dirname, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
// ★ 加固验收（2026-10-04）。与 `verifyApk()` 同源：构建时与 `--verify` 走同一份实现。
import { checkHardening } from './lib/apk-hardening.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ANDROID = join(ROOT, 'android');
const OUT_DIR = join(ROOT, 'apk-out');
/**
 * ★★ 归档根目录（2026-10-04 起）：**一版一目录，只增不改**。
 *
 * 用户明确要求：每次生成新 APK **不得覆盖/替换/删除**上一版，且
 * **每产出一个 APK 必须同步备份该版本对应的源码**，做到一一对应、可追溯。
 *
 * 目录形态（`<buildId>` 见 `makeBuildId()`）：
 *   release/
 *     INDEX.md                     ← 只追加的历史索引（人读）
 *     <buildId>/
 *       ai爱-内置欣然-<buildId>.apk
 *       ai爱-不内置欣然-<buildId>.apk
 *        ai爱-源码-<buildId>.zip    ← 与同目录 APK **同一次构建**产出 ⇒ 天然一一对应
 *       MANIFEST.json              ← 对应关系 + 校验和 + 构建元数据（机器读）
 *       SHA256SUMS.txt             ← 便于 `sha256sum -c` 独立复核
 *
 * ★ 为什么"同目录"就是对应关系：不是靠命名约定去"猜"哪个源码配哪个包，
 *   而是让它们**在物理上属于同一次构建的同一个目录**。命名会被人改错，目录结构不会。
 */
const RELEASE_DIR = join(ROOT, 'release');

/** 两个 flavor 的定义（与 `android/app/build.gradle` 的 productFlavors 一一对应） */
const VARIANTS = {
  builtin: {
    env: '1',
    /** flavor 名（与 build.gradle 的 productFlavors 键、Gradle 任务名的中缀一致） */
    flavor: 'builtin',
    gradleTask: 'assembleBuiltinRelease',
    apkName: 'ai爱-内置欣然-{buildId}.apk',
    appId: 'com.aiai.builtin',
    /**
     * ★ 应用名 = 「ai爱」，**两个版本同名**（用户 2026-10-04 明确要求）。
     *   这个名字会被**两处**校验用：`capacitor.config.json` 的 `appName`、
     *   以及 `aapt2 dump badging` 读出的 `application-label`。
     *   改这里必须同步改 `android/app/build.gradle` 的 flavor `resValue` 与 `capacitor.config.ts`
     *   —— 三处必须一致，否则 build 期的验收会直接判失败（这是有意的）。
     */
    appName: 'ai爱',
    /** APK/产物里**应当存在**的种子特征（内置版才有） */
    expectMarkers: ['创建内置欣然卡失败', '创建默认会话失败', '和欣然'],
  },
  standalone: {
    env: '0',
    flavor: 'standalone',
    gradleTask: 'assembleStandaloneRelease',
    apkName: 'ai爱-不内置欣然-{buildId}.apk',
    appId: 'com.aiai.standalone',
    appName: 'ai爱',
    /** 不内置版：上述种子特征**必须全部消失**（rollup 的 DCE 会把整个分支删掉） */
    expectMarkers: [],
  },
};

/** 不内置版必须**不再出现**的特征（用来验证 DCE 真的生效了） */
const FORBIDDEN_MARKERS = ['创建内置欣然卡失败', '创建默认会话失败', '和欣然'];

/**
 * 跑一个子进程（**异步**），默认把输出实时透传到本进程的 stdout/stderr。
 *
 * ★ 为什么必须用异步 `spawn` 而不是 `execFileSync`（原实现，实测踩坑）：
 *
 *   本环境下 Node 的**同步**子进程 API 全线失效 —— `spawnSync` / `execFileSync` /
 *   `execSync` 一律返回 `EBUSY`，**连 spawn `cmd.exe` 都失败**；而同进程内换成
 *   异步 `spawn` 立刻正常。已实测对照（同一台机器、同一 shell）：
 *       node → spawnSync('cmd.exe')      → EBUSY
 *       node → spawn('cmd.exe')          → 正常
 *       python → subprocess.run(任意)     → 正常
 *       bash → 任意命令                   → 正常
 *   ⇒ 这是环境特性，不是脚本逻辑问题。但结论一样：**验收/打包链不该依赖同步 spawn**。
 *
 * ★ 顺带解决的两个旧隐患：
 *   1. 旧的 `maxBuffer: 64MB` 是为了兜住 gradle 的长输出；异步 + 直接继承 stdio
 *      后**父进程不缓存任何输出**，这个上限连同"输出超限被杀"的风险一起消失。
 *   2. `execFileSync` 期间父进程完全阻塞，日志是"憋到最后一次性吐出来"的；
 *      异步模式下构建进度实时可见 —— 长构建（gradle 30s~3min）出问题时能立刻看出卡在哪。
 *
 * `shell: true` 仅用于 npm / gradlew —— Windows 上它们是 `.cmd`/`.bat`，
 * CreateProcess 不会自己解析 PATHEXT；直接可执行文件（aapt2 等）走 shell:false。
 */
/**
 * 找到 JDK 的根目录（Gradle 需要 JAVA_HOME）。
 *
 * ★ 为什么要自动找：本机 `JAVA_HOME` 默认是**空的**（JDK 是我们为这个项目临时装的，
 *   没进系统环境变量）。手工跑一次忘了传，Gradle 就会抛一个跟"Java 版本"有关的
 *   误导性错误（实测报过 `无效的源发行版：21`，看着像版本装错了，其实只是没找到 JDK）。
 *   ⇒ 把探测逻辑固化进脚本：环境变量 → 常见工具链目录 → PATH 上的 java。
 *
 * ★ 必须 ≥ 21：`android/app/capacitor.build.gradle` 硬编码 `JavaVersion.VERSION_21`，
 *   而那个文件首行写明 `DO NOT EDIT THIS FILE!`（每次 cap update 会被覆盖），
 *   ⇒ **不能降级文件，只能满足它**。所以这里优先挑版本号大的 JDK。
 */
function resolveJavaHome() {
  const candidates = [];

  if (process.env.JAVA_HOME && existsSync(join(process.env.JAVA_HOME, 'bin'))) {
    candidates.push(process.env.JAVA_HOME);
  }
  // 本项目自建的 Android 工具链（见 docs/06 的环境搭建一节）
  const toolchain = join(process.env.USERPROFILE ?? process.env.HOME ?? '', '.workbuddy', 'android-toolchain');
  if (existsSync(toolchain)) {
    for (const d of readdirSync(toolchain)) {
      if (/^jdk/i.test(d)) candidates.push(join(toolchain, d));
    }
  }
  // PATH 上的 java → 回推两级（.../bin/java → ...bin → JDK 根）
  for (const p of (process.env.PATH ?? '').split(process.platform === 'win32' ? ';' : ':')) {
    if (p && existsSync(join(p, process.platform === 'win32' ? 'java.exe' : 'java'))) {
      candidates.push(dirname(p));
    }
  }
  // 兼容 "JAVA_HOME 直接指向 bin" 的常见误配
  if (process.env.JAVA_HOME && existsSync(process.env.JAVA_HOME)) {
    candidates.push(dirname(process.env.JAVA_HOME));
  }

  const usable = candidates.filter((c) => c && existsSync(join(c, 'bin')));
  if (usable.length === 0) return null;

  // 版本号大的优先（21 优于 17，见上方注释）
  const verOf = (p) => {
    const m = /(?:jdk[-_])?(\d+)(?:[.\-_](\d+))?/.exec(p.split(/[\\/]/).pop() ?? '');
    return m ? Number(m[1]) * 1000 + Number(m[2] ?? 0) : 0;
  };
  usable.sort((a, b) => verOf(b) - verOf(a));
  return usable[0];
}

/** 模块级解析一次：`main()` 只负责打印，`buildVariant()` 直接用它注入 gradle 环境 */
const JAVA_HOME = resolveJavaHome();

const run = (cmd, args, opts = {}) => {
  return new Promise((resolve, reject) => {
    if (!opts.silent) process.stdout.write(`\n\x1b[36m$ ${cmd} ${args.join(' ')}\x1b[0m\n`);
    const child = spawn(cmd, args, {
      cwd: opts.cwd ?? ROOT,
      env: { ...process.env, ...opts.env },
      shell: opts.shell ?? process.platform === 'win32',
      stdio: opts.capture ? ['ignore', 'pipe', 'pipe'] : 'inherit',
      windowsHide: true,
    });

    let out = '';
    let err = '';
    if (opts.capture) {
      child.stdout.setEncoding('utf8');
      child.stderr.setEncoding('utf8');
      child.stdout.on('data', (d) => {
        out += d;
      });
      child.stderr.on('data', (d) => {
        err += d;
      });
    }

    child.on('error', (e) => reject(new Error(`${cmd} 启动失败：${e.message}`)));
    child.on('close', (code) => {
      if (code === 0) resolve(out);
      else {
        const e = new Error(`${cmd} 退出码 ${code}${err ? `\n${err.trim().slice(-1500)}` : ''}`);
        e.exitCode = code;
        e.stdout = out;
        e.stderr = err;
        reject(e);
      }
    });
  });
}

function readVersion() {
  // 从 build.gradle 读 versionName（避免和 gradle 的版本号两处维护）
  const text = readFileSync(join(ANDROID, 'app', 'build.gradle'), 'utf8');
  const m = /versionName\s+["']([^"']+)["']/.exec(text);
  return m ? m[1] : '1.0';
}

/** 同 readVersion，但读 versionCode（写进 MANIFEST 便于与安装包对账） */
function readVersionCode() {
  const text = readFileSync(join(ANDROID, 'app', 'build.gradle'), 'utf8');
  const m = /versionCode\s+(\d+)/.exec(text);
  return m ? Number(m[1]) : 0;
}

/* ══════════════════════════════════════════════════════════════════════════
 * 版本归档（2026-10-04 起，用户明确要求的长期约定）
 * ══════════════════════════════════════════════════════════════════════════ */

/**
 * 生成**唯一且可排序**的构建号。
 *
 * ★ 命名规则（2026-10-04 用户指定，**简化过**）：
 *   `v1`、`v2`、`v3` …… 依次递增，一个版本一个号。
 *
 * 上一版用的是 `v<versionName>-b<YYYYMMDD>-<HHMMSS>`（例 `v1.0-b20261004-163800`），
 * 用户明确要求换成简单递增号，理由很实际：**那串时间戳对人没有意义**，
 * 想指代"上一版"时既难念也难记，而 `v1`→`v2` 的顺序一眼就懂。
 *
 * ★ 为什么是"扫描目录取最大值 +1"而不是维护一个计数器文件：
 *   计数器文件本身就是一处会写坏、会被并发打断、会被误删的共享状态；
 *   **目录列表才是唯一事实来源** —— 目录在，编号就不会重。
 *   这样"编号"与"实际存在的版本"天然一致，不存在两边对不上的可能。
 *
 * ★ 绝不覆盖：即使编号真撞上（并发构建），下面的**碰撞守卫**会直接报错退出，
 *   不会静默覆盖 —— 这是用户反复强调的要求。
 */
function nextBuildNumber() {
  if (!existsSync(RELEASE_DIR)) return 1;
  const nums = readdirSync(RELEASE_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    // 只认严格的 `v<数字>`，不认历史上的 `v1.0-b2026…` / `v0-legacy-…`
    .map((e) => /^v(\d+)$/.exec(e.name))
    .filter((m) => m !== null)
    .map((m) => Number(m[1]));
  return nums.length > 0 ? Math.max(...nums) + 1 : 1;
}

function makeBuildId() {
  return `v${nextBuildNumber()}`;
}

/** 文件 SHA-256（归档完整性用；分块读，避免把 6MB 包整个驻留内存） */
function sha256File(filePath) {
  const h = createHash('sha256');
  const fd = openSync(filePath, 'r');
  try {
    const buf = Buffer.alloc(1024 * 512);
    let pos = 0;
    for (;;) {
      const n = readSync(fd, buf, 0, buf.length, pos);
      if (n <= 0) break;
      h.update(buf.subarray(0, n));
      pos += n;
    }
  } finally {
    closeSync(fd);
  }
  return h.digest('hex');
}

/**
 * git 状态（记进 MANIFEST，让"这一版对应哪份代码"可追溯）。
 *
 * ★ 用 `run()` 而不是 `execFileSync`：本环境 Node 的**同步**子进程 API 全线 EBUSY
 *   （详见文件上方 `run()` 的长注释）。我第一版在这里写了 `require('node:child_process')`
 *   —— 那是**错的**，本文件是 ESM，`require` 根本不存在。改成复用已有的异步 `run()`。
 *
 * ★ git 取不到（非仓库 / 命令失败）**不能**让打包失败：它是元数据，不是构建前提。
 */
/**
 * 把该版本的**源码备份**生成到同一个目录里。
 *
 * ★ 为什么直接调 `scripts/backup-source.py`（而不是在这里重写一遍打包逻辑）：
 *   那份脚本已经处理了"排除清单"（依赖/产物/测试输出/**签名私钥**）与"打包后自检"，
 *   并有自己的长注释说明每一条排除的理由。复制一份逻辑 = 两处会漂移的真相。
 *
 * ★ 失败必须**大声失败**：用户要求"每产出一个 APK 都必须同步备份源码"，
 *   静默降级成"只有 APK 没有源码"就违背了这条要求本身。
 */
async function backupSourceInto(buildDir, buildId) {
  const py = process.env.PYTHON ?? 'python';
  const script = join(ROOT, 'scripts', 'backup-source.py');
  if (!existsSync(script)) throw new Error(`找不到源码备份脚本：${script}`);
  // `--out-dir` 收绝对路径；`--name` 决定文件名前缀（内部会拼 `-<日期>.zip`）
  await run(py, [script, '--out-dir', buildDir, '--name', `ai爱-源码-${buildId}`], { shell: false });
}

/**
 * 写 `MANIFEST.json` —— 机器可读的**版本对应关系**。
 *
 * ★ 这是"可追溯"的核心载体：它把「哪个 APK」↔「哪份源码备份」↔「哪一次 git 状态」
 *   三者的关系固化在一个文件里，而不是靠人记或靠文件名猜。
 */
function writeManifest(buildDir, info) {
  const p = join(buildDir, 'MANIFEST.json');
  writeFileSync(p, `${JSON.stringify(info, null, 2)}\n`);
  return p;
}

/** 写 `SHA256SUMS.txt`（`sha256sum -c` 可直接复核，不依赖我们的脚本） */
function writeSums(buildDir, entries) {
  const lines = entries.map((e) => `${e.sha256}  ${e.file}`);
  const p = join(buildDir, 'SHA256SUMS.txt');
  writeFileSync(p, `${lines.join('\n')}\n`);
  return p;
}

/**
 * 往 `release/INDEX.md` **追加**一行索引。
 *
 * ★ 为什么是"追加"而不是"重写"：用户要求保留所有历史版本。
 *   重写会丢掉早期记录 —— 而索引恰恰是"历史上打过哪些包"的唯一汇总。
 *   用 append 语义，文件本身也不存在"被覆盖"的可能。
 *
 * ★ 表头与 2026-10-04 的**命名规则变更**同步（改为 `v1`/`v2` 递增后，列也简化了：
 *   去掉 `versionName/code`、`git HEAD`、`未提交` 三列 —— 构建号本身就够指代一个版本，
 *   那些信息在各自 `MANIFEST.json` 里都有，索引里堆着反而不好读）。
 *   ⚠️ 这个 `head` 只在 INDEX.md **不存在**时使用；已有的 INDEX.md 不会被改写，
 *      所以改表头**不会**影响历史记录。
 */
function appendIndex(info) {
  const indexPath = join(RELEASE_DIR, 'INDEX.md');
  const first = !existsSync(indexPath);
  const head = [
    '# APK 版本归档索引',
    '',
    '> 本文件**只追加、不重写**（每次构建追加一行）。由 `scripts/build-apk.mjs` 自动维护。',
    '> 每个版本一个目录，目录内同时含 APK 与该版本源码备份 ⇒ 一一对应、可追溯。',
    '',
    '命名规则：`v<N>`（N 从 1 开始递增）',
    '',
    '| 版本 | 构建时间 | 原构建号 | APK | 源码备份 | 源码对应 |',
    '|---|---|---|---|---|---|',
  ].join('\n');

  const apkList = info.variants.map((v) => v.file).join('<br>');
  // 本行是"新构建"，它不是从旧名重编号来的 ⇒ 原构建号列写 `—`
  const row = `| \`${info.buildId}\` | ${info.builtAt} | — | ${apkList} | ${info.sourceBackup.file} | ✓ |`;

  if (first) {
    // 首次创建：表头 + 第一行，直接写
    writeFileSync(indexPath, `${head}\n${row}\n`, 'utf8');
    return indexPath;
  }

  /* ══════════════════════════════════════════════════════════════════════════
   * ★★ 非首次：把新行**插进版本表格**，而不是追加到文件末尾。
   *
   * ── 为什么必须改（2026-10-04 实测踩到）──
   * 原实现是 `appendFileSync(indexPath, row + '\n')` —— 无条件写到**文件末尾**。
   * 这在"INDEX.md 只有一个表格"时没问题，但本项目后来手工重建过 INDEX.md
   * （加了「★ 各版本发生了什么（读表指南）」「怎么用」「两条必须知道的边界」等章节），
   * 表格**后面还有正文** ⇒ 追加的行落到了文件末尾，
   * 变成"表格里缺 v9/v10、文件末尾却孤零零挂两行表格语法"。
   *
   * 实测现象：v8、v9、v10 连续三版都被追加到末尾，每次都要人工搬回去。
   * 一个每次都要人工补救的自动化，等于没有自动化。
   *
   * ── 修法 ──
   * 找到表格里**最后一个数据行**（形如 `| \`vN\` | ...`），把新行插在它后面。
   * 找不到表格就退回 append（保证"至少不会丢数据"）。
   *
   * ★ 仍然坚持"不截断"的安全原则：
   *   全程 `readFileSync` 读原文 → 只做一次 `splice` 插入 → `writeFileSync` 写回，
   *   **除插入的那一行外，其余字节原样保留**。
   *   并在写回前断言"新内容 = 旧内容 + 新行"，不一致就放弃写入并告警 ——
   *   宁可这一行不写，也不能把索引写坏（它是"历史上打过哪些包"的唯一汇总）。
   * ══════════════════════════════════════════════════════════════════════════ */
  const original = readFileSync(indexPath, 'utf8');
  const lines = original.split('\n');

  /**
   * 表格数据行的判据。
   *
   * ★★ 这里必须能区分 INDEX.md 里的**两张**表格（踩过才知道）：
   *   ① 「版本归档表」6 列：`| \`v10\` | 10-04 21:44 | — | APK | 源码 | ✓ |`
   *   ② 「各版本发生了什么」3 列：`| \`v7\` | ✅ 可用 | 在 v6 基础上… |`
   *
   *   只写「以 `| \`vN\` |` 开头」的话，**两张表都会被匹配到** ——
   *   而 ② 在 ① 的**后面**，于是从尾部往前找会先撞上 ②，
   *   新行被插进「各版本发生了什么」表里（位置完全错、还会破坏那张表的语义）。
   *
   *   ⇒ 判据锚在**第 2 列的内容**上：① 的第 2 列是时间（`MM-DD HH:mm` 或 ISO），
   *     ② 的第 2 列是状态文字（`✅ 可用` 之类）。
   *     用"是不是时间"区分，比用列数更稳 —— 将来某张表加一列，列数判据就失效了。
   */
  const isDataRow = (l) => /^\|\s*`v\d+`\s*\|\s*(\d{2}-\d{2}|20\d{2}-)/.test(l);

  let lastIdx = -1;
  for (let i = lines.length - 1; i >= 0; i -= 1) {
    if (isDataRow(lines[i])) {
      lastIdx = i;
      break;
    }
  }

  if (lastIdx === -1) {
    // 找不到表格（文件被人改过形态）⇒ 退回 append，但明确告警
    console.warn(`⚠️  INDEX.md 里找不到版本表格，新行按旧行为追加到末尾（请人工确认位置）`);
    appendFileSync(indexPath, `${row}\n`);
    return indexPath;
  }

  lines.splice(lastIdx + 1, 0, row);
  const next = lines.join('\n');

  /**
   * ★ 安全断言：把刚插入的那一行**去掉**后，必须能逐字节还原成原文。
   *   任一不成立就不写盘 —— 宁可少一行记录（可人工补），也不能把索引写坏。
   *
   * ★ 注意断言的写法：**必须在 splice 之后重新拼一份"去掉新行"的副本**再去比。
   *   第一版写的是"用已 splice 过的 lines 拼 expected 再和 next 比"——
   *   两个都由同一个数组拼出来，**恒等**，等于没有断言（假断言比没有更糟：
   *   它会让人以为这里有保护）。
   */
  const restored =
    lines.slice(0, lastIdx + 1).join('\n') +
    (lines.length > lastIdx + 2 ? '\n' + lines.slice(lastIdx + 2).join('\n') : '');
  if (restored !== original) {
    console.warn('⚠️  INDEX.md 插入校验不通过，已放弃写入（索引保持原样，请人工补一行）');
    return indexPath;
  }
  writeFileSync(indexPath, next, 'utf8');
  return indexPath;
}

async function gitInfo() {
  try {
    const head = (await run('git', ['rev-parse', 'HEAD'], { capture: true, shell: false, silent: true })).trim();
    let dirty = 0;
    try {
      const status = await run('git', ['status', '--porcelain'], { capture: true, shell: false, silent: true });
      dirty = status.trim() === '' ? 0 : status.trim().split('\n').length;
    } catch {
      /* 忽略：dirty 计数取不到就当 0，不影响归档 */
    }
    return { head: head || '(非 git 仓库)', dirty };
  } catch {
    return { head: '(非 git 仓库)', dirty: 0 };
  }
}

/** 找到 gradle 产出的 APK（flavor 目录名 = builtin/standalone） */
function findApk(variant) {
  const dir = join(ANDROID, 'app', 'build', 'outputs', 'apk', variant, 'release');
  if (!existsSync(dir)) return null;
  const apks = readdirSync(dir).filter((f) => f.endsWith('.apk'));
  if (apks.length === 0) return null;
  return join(dir, apks[0]);
}

/* ══════════════════════════════════════════════════════════════════════════
 * 纯 Node 的最小 zip 读取器
 *
 * ★ 为什么不用 `unzip` 命令（原实现就是它，实测踩坑）：
 *
 *   上一版用 `execFileSync('unzip', ...)` 读产物，构建到最后一步报：
 *       spawnSync unzip EBUSY
 *   `EBUSY`(Windows ERROR_BUSY) 发生在 **spawn 阶段**，不是解压阶段 —— 即
 *   `unzip.exe` 或其所在目录在那一瞬间被别的进程占着（实时杀毒扫描、Windows
 *   搜索索引、刚被 Gradle 写出的 APK 自身的句柄延迟释放，三个都可能）。
 *   这不是我们代码的逻辑错误，**但会把一个好端端的包判成失败**，而且失败点
 *   在"验收"这一步 —— 产物其实已经出来了，只是没人能读它。
 *
 *   ⇒ 结论：验收环节**不该依赖外部可执行文件**。APK 就是个 zip，Node 自带
 *     `zlib.inflateRawSync`，按中央目录读一遍只要几十行，且**没有任何竞态**。
 *
 * ★ 实现取舍（写清以免将来被"优化"掉）：
 *   - 只走**中央目录**（EOCD → CD → local header）。CD 里的 `compressedSize`
 *     是权威值，即使写入方用了 data descriptor（local header 中该字段为 0）
 *     也不受影响。
 *   - **不支持 Zip64**。本项目 APK ~6 MB、条目数 < 65535，用不到；
 *     若将来看见 `0xFFFFFFFF` 的 size/offset 哨兵值，需要补 Zip64 分支。
 *   - 只支持 stored(0) 与 deflate(8) —— 这也是 APK 里唯一会出现的两种。
 * ══════════════════════════════════════════════════════════════════════════ */

/** 读中央目录，返回 { fd, entries }。调用方负责 closeZip()。 */
function openZip(filePath) {
  const fd = openSync(filePath, 'r');
  try {
    const size = fstatSync(fd).size;

    // EOCD 在文件末尾，最长 22 + 65535（注释）字节
    const tailLen = Math.min(size, 65557);
    const tail = Buffer.alloc(tailLen);
    readSync(fd, tail, 0, tailLen, size - tailLen);

    let eocd = -1;
    for (let i = tail.length - 22; i >= 0; i -= 1) {
      if (tail.readUInt32LE(i) === 0x06054b50) {
        eocd = i;
        break;
      }
    }
    if (eocd < 0) throw new Error(`${filePath} 不是有效的 zip（找不到 EOCD）`);

    const entryCount = tail.readUInt16LE(eocd + 10);
    const cdSize = tail.readUInt32LE(eocd + 12);
    const cdOffset = tail.readUInt32LE(eocd + 16);

    const cd = Buffer.alloc(cdSize);
    readSync(fd, cd, 0, cdSize, cdOffset);

    const entries = [];
    let p = 0;
    for (let i = 0; i < entryCount; i += 1) {
      if (p + 46 > cd.length || cd.readUInt32LE(p) !== 0x02014b50) break;
      const method = cd.readUInt16LE(p + 10);
      const compSize = cd.readUInt32LE(p + 20);
      const uncompSize = cd.readUInt32LE(p + 24);
      const nameLen = cd.readUInt16LE(p + 28);
      const extraLen = cd.readUInt16LE(p + 30);
      const commentLen = cd.readUInt16LE(p + 32);
      const localOffset = cd.readUInt32LE(p + 42);
      const name = cd.toString('utf8', p + 46, p + 46 + nameLen);
      entries.push({ name, method, compSize, uncompSize, localOffset });
      p += 46 + nameLen + extraLen + commentLen;
    }
    return { fd, entries };
  } catch (e) {
    closeSync(fd);
    throw e;
  }
}

const closeZip = (z) => closeSync(z.fd);

/** 取出单个条目的解压后内容（Buffer）。 */
function readZipEntry(zip, entry) {
  // local header 的 extra 长度与中央目录的**不一定相同**，必须重新读
  const lh = Buffer.alloc(30);
  readSync(zip.fd, lh, 0, 30, entry.localOffset);
  if (lh.readUInt32LE(0) !== 0x04034b50) {
    throw new Error(`local header 损坏：${entry.name}`);
  }
  const nameLen = lh.readUInt16LE(26);
  const extraLen = lh.readUInt16LE(28);
  const dataStart = entry.localOffset + 30 + nameLen + extraLen;

  const raw = Buffer.alloc(entry.compSize);
  if (entry.compSize > 0) readSync(zip.fd, raw, 0, entry.compSize, dataStart);

  if (entry.method === 0) return raw;
  if (entry.method === 8) return inflateRawSync(raw);
  throw new Error(`不支持的压缩方式 ${entry.method}：${entry.name}`);
}

/**
 * 用 `aapt2 dump badging` 读 APK 的**真实清单**（应用名 / 包名 / 图标 / 权限 / SDK 版本）。
 *
 * ★ 这是唯一能穿透 AGP 资源改名与 `resources.arsc` 的读法，所以版本验收以它为准。
 *   但它是外部进程，且此刻 APK 刚写完 ⇒ 保留 try/catch：**失败只记 note 不判死**
 *   （`EBUSY` 的教训见上方 openZip 注释 —— 验收脚本不该因为环境抖动把人骗到错误的结论上）。
 */
function findAapt2() {
  const p = join(ANDROID, 'local.properties');
  if (!existsSync(p)) return null;
  const m = /^sdk\.dir\s*=\s*(.+)$/m.exec(readFileSync(p, 'utf8'));
  if (!m) return null;
  const sdkDir = m[1].trim().replace(/\\/g, '/');
  const btRoot = join(sdkDir, 'build-tools');
  if (!existsSync(btRoot)) return null;
  const ver = readdirSync(btRoot).sort().reverse()[0];
  const aapt2 = join(btRoot, ver, process.platform === 'win32' ? 'aapt2.exe' : 'aapt2');
  return existsSync(aapt2) ? aapt2 : null;
}

async function tryBadging(apkPath) {
  try {
    const aapt2 = findAapt2();
    if (!aapt2) return { ok: false, reason: '找不到 aapt2（检查 android/local.properties 的 sdk.dir）' };

    const out = await run(aapt2, ['dump', 'badging', apkPath], { capture: true, shell: false });
    const grab = (re) => {
      const m = re.exec(out);
      return m ? m[1] : null;
    };
    return {
      ok: true,
      packageName: grab(/^package: name='([^']+)'/m),
      versionName: grab(/^package:.*versionName='([^']+)'/m),
      versionCode: grab(/^package:.*versionCode='([^']+)'/m),
      label: grab(/^application-label:'([^']*)'/m),
      launchable: /^launchable-activity:/m.test(out),
      icons: (out.match(/^application-icon-[^\n]*/gm) ?? []).length,
      sdk: grab(/^sdkVersion:'([^']+)'/m),
      targetSdk: grab(/^targetSdkVersion:'([^']+)'/m),
      permissions: (out.match(/^uses-permission: name='([^']+)'/gm) ?? []).map((s) =>
        s.replace(/^uses-permission: name='|'$/g, ''),
      ),
    };
  } catch (e) {
    return { ok: false, reason: e.message.split('\n')[0] };
  }
}

/**
 * ★ 关键校验（**唯一验收入口**）：确认 APK 的版本特征与清单都与预期一致。
 *
 * 两层检查，缺一不可：
 *   ① 解出打进包的 JS bundle，比对**种子分支独有**的字符串（判据见 `src/constants/buildMode.ts`）；
 *   ② `aapt2 dump badging` 读**真实清单**（包名/应用名/权限/SDK），穿透 AGP 的资源改名。
 *   只读需要的 zip 条目，不解全包，避免把上百 MB 的中间产物写盘。
 */
async function verifyApk(apkPath, variant) {
  const cfg = VARIANTS[variant];
  const zip = openZip(apkPath);
  const problems = [];
  const notes = [];
  const found = new Set();
  let checked = 0;

  try {
    const jsEntries = zip.entries.filter(
      (e) => e.name.startsWith('assets/public/assets/') && e.name.endsWith('.js'),
    );
    if (jsEntries.length === 0) {
      problems.push('APK 里没有 assets/public/assets/*.js —— web 产物没被打进去？');
    }

    for (const e of jsEntries) {
      let body;
      try {
        body = readZipEntry(zip, e).toString('utf8');
      } catch {
        continue; // 单个 chunk 读不动不算致命，交给"特征缺失"去报
      }
      checked += 1;
      for (const m of FORBIDDEN_MARKERS) {
        if (body.includes(m)) found.add(m);
      }
    }

    // 原生配置：appId / appName 是否与 flavor 一致
    const cfgEntry = zip.entries.find((e) => e.name === 'assets/capacitor.config.json');
    if (!cfgEntry) {
      problems.push('读不到 assets/capacitor.config.json');
    } else {
      const cfgJson = readZipEntry(zip, cfgEntry).toString('utf8');
      if (!cfgJson.includes(cfg.appId)) {
        problems.push(`capacitor.config.json 的 appId 不是 ${cfg.appId}`);
      }
      if (!cfgJson.includes(cfg.appName)) {
        problems.push(`capacitor.config.json 的 appName 不是 ${cfg.appName}`);
      }
      if (cfgJson.includes('"dist"') === false) {
        problems.push('capacitor.config.json 缺少 webDir=dist');
      }
    }

    // 图标 / 清单：**软检查**，只报告不判死。
    // ★ 为什么不做成硬断言：AGP 8 的 release 构建默认开启 resource path shortening
    //   （`android.enableResourceOptimizations`），`res/mipmap-xxx/ic_launcher.png`
    //   会被改名成 `res/9D.png` 这类短路径，字符串也大量挪进 resources.arsc。
    //   按原路径断言必然假红 —— 而"假红"比"没检查"更糟：它会让人开始怀疑验收结果。
    //   真正的图标验收走 `aapt2 dump badging`（见下方 notes）与源图目视比对。
    const resEntries = zip.entries.filter((e) => e.name.startsWith('res/'));
    notes.push(`res/ 条目 ${resEntries.length} 个${resEntries.length === 0 ? ' ⚠️ 异常' : ''}`);
    notes.push(
      zip.entries.some((e) => e.name === 'resources.arsc') ? '含 resources.arsc ✓' : '缺少 resources.arsc ⚠️',
    );
    notes.push(
      zip.entries.some((e) => e.name === 'AndroidManifest.xml') ? '含 AndroidManifest.xml ✓' : '缺少 AndroidManifest.xml ⚠️',
    );
  } finally {
    closeZip(zip);
  }

  // 内置版：三个种子特征**应当都在**
  for (const m of cfg.expectMarkers) {
    if (!found.has(m)) problems.push(`缺少内置版特征「${m}」`);
  }
  // 不内置版：**一个都不该在**
  if (variant === 'standalone') {
    for (const m of FORBIDDEN_MARKERS) {
      if (found.has(m)) problems.push(`不该出现的内置版特征「${m}」`);
    }
  }

  /* ── 权威清单核对（aapt2）──────────────────────────────────────────────   * ★ 为什么这部分必须放在验收函数**内部**、而不是构建流程里：
   *   上一版把权限断言写在 `buildVariant()` 里，结果 `--verify` 路径**漏掉了它** ——
   *   同一份验收标准存在两个实现，其中一个还是残的。这类"验收路径不一致"最阴：
   *   重新打包时通过、事后复验时也"通过"，但两者查的根本不是同一组东西。
   *   ⇒ 验收逻辑只此一处，任何入口（构建时 / 事后复验）都走它。
   */
  const badging = await tryBadging(apkPath);
  if (!badging.ok) {
    notes.push(`⚠️ aapt2 清单核对跳过（${badging.reason}）—— 包名/应用名/权限未经权威核对`);
  } else {
    notes.push(
      `清单：package=${badging.packageName} label="${badging.label}" ` +
        `versionName=${badging.versionName} min=${badging.sdk} target=${badging.targetSdk}`,
    );
    notes.push(
      `图标密度档 ${badging.icons} 个｜启动 Activity ${badging.launchable ? '✓' : '✗'}｜` +
        `权限 [${badging.permissions.join(', ') || '无'}]`,
    );

    if (badging.packageName !== cfg.appId) {
      problems.push(`APK 包名是 ${badging.packageName}，应为 ${cfg.appId}`);
    }
    if (badging.label !== cfg.appName) {
      problems.push(`APK 应用名是「${badging.label}」，应为「${cfg.appName}」`);
    }
    if (!badging.launchable) problems.push('APK 没有可启动的 Activity —— 装上去点不开');
    if (!(badging.icons > 0)) problems.push('APK 没有任何 application-icon —— 没有图标');

    // 权限白名单：只允许「联网」与 Capacitor 的应用私有权限。
    // ★ 断言写法的坑（实测）：最初白名单只写了 INTERNET / ACCESS_NETWORK_STATE，
    //   于是 standalone 版被判成「出现意料外权限」而**整包构建失败** —— 但那条
    //   `com.aiai.standalone.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION` 是
    //   **Capacitor 自己生成的**（满足 Android 14 对 registerReceiver 的显式导出要求），
    //   以 **applicationId 为前缀**，所以每个 flavor 各有一份、互不相同。
    //   这不是产品问题，是**断言漏了这一条** ⇒ 用 cfg.appId 参数化。
    const allowed = new Set([
      'android.permission.INTERNET',
      'android.permission.ACCESS_NETWORK_STATE',
      `${cfg.appId}.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION`,
      // ★ `CAMERA`（2026-10-04 加，聊天的「拍照」按钮）。
      //   这条是**必须进白名单**的：WebView 的 `getUserMedia` 在安卓上要经过
      //   `onPermissionRequest → CAMERA 运行时申请`，而申请的前置条件是
      //   **AndroidManifest 里声明过它**。
      //   ⇒ 漏了声明 ⇒ 系统权限弹窗根本不出现、JS 收到 NotAllowedError
      //     （一个把人引向"用户拒绝了权限"这个错误结论的假象）。
      //   加进白名单 = 让"声明过相机权限"成为可被断言的事实。
      'android.permission.CAMERA',
    ]);
    const unexpected = badging.permissions.filter((p) => !allowed.has(p));
    if (unexpected.length > 0) problems.push(`出现意料外的权限：${unexpected.join(', ')}`);

    // 反向断言：联网权限必须真的在。没有它，LLM 请求全废但**界面不会崩**，
    // 用户只会看到"连不上" —— 属于最难排查的一类交付缺陷。
    if (!badging.permissions.includes('android.permission.INTERNET')) {
      problems.push('缺少 android.permission.INTERNET —— 应用将无法访问 LLM 接口');
    }

    // 反向断言：相机权限必须真的在（2026-10-04 加）。
    // ★ 与 INTERNET 那条同理，但失败表现更隐蔽：缺 INTERNET 是"连不上"（用户能描述），
    //   缺 CAMERA 是"点了拍照没反应"（用户只知道坏了，说不出哪儿坏了）。
    //   而且**不会报权限错误**（系统没弹窗、设置里也没有该开关）——
    //   属于"静默不可用"，只能靠断言兜住。
    if (!badging.permissions.includes('android.permission.CAMERA')) {
      problems.push('缺少 android.permission.CAMERA —— 聊天里的「拍照」按钮会静默失效（点了一点反应都没有）');
    }
  }

  /* ── ★ 加固验收（2026-10-04 加）──────────────────────────────────────
   * ★ 为什么放在这里、而不是新开一个入口：
   *   同上面那段注释讲的是同一件事 —— **验收逻辑只此一处**。
   *   `--verify` 事后复验也走这个函数，所以加固断言在"构建时"和"事后复验"
   *   两条路径上是同一份实现，不会出现"重新打包通过、复验更严"这类不一致。
   *
   * ★ 它验的是**产物**，不是配置：
   *   `minifyEnabled true` 写在 build.gradle 里不代表混淆真的跑了
   *   （可能被 flavor 覆盖、可能 keep 规则写太宽而什么都没改名）。
   *   所以判据全部从 dex / 清单 / 签名里反推，见 `scripts/lib/apk-hardening.mjs`。
   */
  const hardening = await checkHardening(apkPath, { root: ROOT, env: JAVA_HOME ? { JAVA_HOME } : {} });
  for (const p of hardening.problems) problems.push(`[加固] ${p}`);
  for (const n of hardening.notes) notes.push(n);

  return { problems, notes, checked, found: [...found], badging, hardening: hardening.metrics };
}

/**
 * 让开 flavor 的 assets 目录，保证同步后内容**恰好等于** `dist`。
 *
 * ★ 三版实现的血泪史（写清，别退回前两版）：
 *
 *   v1「只覆盖同名、不删旧文件」——
 *     内容哈希文件名意味着每次构建都产生一批**新名字**，旧文件永久堆积。
 *     实测：重复构建后 flavor 目录累积 109 个死文件，内置版 APK 从 5.7 MB 涨到 6.6 MB。
 *     死文件不影响功能（`index.html` 只引用本次哈希），但**产物不可复现** ——
 *     同一 commit 在不同构建历史上打出不同体积的包。
 *
 *   v2「逐文件 unlink 回收陈旧项」——**实测无效，已废弃**。
 *     构建日志如实记录：`[prune] 回收 0/109 个陈旧产物` —— 找到了 109 个，一个都没删掉。
 *     （单独跑一个脚本删 1 个文件是成功的，但在 Gradle 构建进程的上下文里 109 个连续
 *      unlink **全部失败**，且被 catch 静默吞掉 ⇒ 看起来"做了清理"，实际零效果。
 *     这是"静默失败比不做更糟"的又一例：它让体积异常看起来已经被解释了。）
 *
 *   v3（当前）「**rename 让开目录，而不是删文件**」——
 *     `renameSync` 在本环境是**可用**的（`clean-dist.mjs` 一直靠它把旧产物搬进暂存区，
 *     日志里的「搬走 83 个文件…零删除」就是它）。而且只需 **1 次** rename 调用，
 *     不是 109 次删除 —— 既能绕开删除守卫，也不依赖逐个操作都成功。
 *     让开后重新建目录、从 `dist` 全新拷入 ⇒ 内容与 `dist` 严格一致，结构上不可能有死文件。
 *
 * ★ 失败兜底：rename 若因任何原因不成功（目录被占用等），**退回 v1 行为**（只覆盖同名）
 *   —— 宁可有死文件，也不能因为清理失败而打不出包。
 */
function resetAssetsDir(pubDir, flavor) {
  if (!existsSync(pubDir)) return { method: 'fresh' };

  const cacheRoot = join(ROOT, 'node_modules', '.cache');
  if (!existsSync(cacheRoot)) mkdirSync(cacheRoot, { recursive: true });
  const aside = join(cacheRoot, `stale-assets-${flavor}-${Date.now()}`);

  try {
    renameSync(pubDir, aside);
    return { method: 'rename', aside };
  } catch (e) {
    // 不让开就退回"只覆盖"（v1）—— 死文件比构建失败可接受得多
    console.warn(
      `  [reset] ⚠️ 让开目录失败（${e.code ?? e.message.split('\n')[0]}）—— 退回"只覆盖同名"，` +
        `可能残留死文件（只增体积，不影响功能）`,
    );
    return { method: 'overwrite' };
  }
}

/**
 * 把 web 产物同步进**该 flavor 专属**的 Android assets 目录。
 *
 * ★ 为什么写 `src/<flavor>/assets/` 而不是共用的 `src/main/assets/`：
 *
 *   1. **结构上不需要删除任何文件。** 共用目录意味着每次切换版本都要先清空上一个版本的产物，
 *      而本环境的文件删除有**批量删除守卫**（>50 个文件要求交互确认）；
 *      后台进程没有 TTY，无法确认 ⇒ 整个打包会**无声挂死**（已实测：日志停住、进程不退）。
 *      改成 per-flavor 目录后，两个版本**各写各的**，永远不需要清空。
 *
 *   2. 这是 Android 的原生惯例（flavor-specific source set）：
 *      Gradle 会把 `src/<flavor>/assets/` 与 `src/main/assets/` 合并，同名时 **flavor 覆盖 main**。
 *      ⇒ 无需自己实现合并逻辑，也不用 `cap sync`。
 *
 *   3. **版本隔离是物理的**：builtin 的产物不可能跑到 standalone 的包里，
 *      不再依赖"记得先清空"这种人为纪律。（`syncWebAssets` 的旧实现正是靠清空来保证隔离，
 *      而清空恰好是被守卫拦住的那一步。）
 *
 * ★ 与 `cap sync` 的关系（边界，写清以免将来踩）：
 *   本函数只做 "copy web assets"，**不做 `cap update`**（同步原生插件：gradle 依赖、cordova 桥）。
 *   本项目未引入任何第三方 Capacitor 插件，故 update 无事可做。
 *   **若将来引入原生插件**（如把 `fetchOrNative` 的原生部分做成插件），
 *   必须改回 `cap sync` 或在此补上 update 逻辑，否则插件不会注册进原生工程。
 */
function syncWebAssets(cfg) {
  // flavor 名 = VARIANTS 的键（builtin / standalone），与 build.gradle 的 productFlavors 一致
  const flavorDir = join(ANDROID, 'app', 'src', cfg.flavor, 'assets');
  const pub = join(flavorDir, 'public');

  const distDir = join(ROOT, 'dist');
  if (!existsSync(distDir)) throw new Error('dist 不存在——上一步 `npm run build` 没产出？');

  // ① 先让开旧目录（rename，不是删除——理由见 resetAssetsDir 的三版历史）
  //    ⇒ 之后再拷，内容就严格等于本次 dist，不可能有陈旧文件残留
  const reset = resetAssetsDir(pub, cfg.flavor);
  if (reset.aside) {
    console.log(`  [reset] 旧产物已让开 → ${reset.aside.replace(ROOT + sep, '')}`);
  }
  mkdirSync(pub, { recursive: true });

  // ② 从 dist 全新拷入
  let copied = 0;
  const copyWalk = (src, dst) => {
    if (!existsSync(dst)) mkdirSync(dst, { recursive: true });
    for (const ent of readdirSync(src, { withFileTypes: true })) {
      const s = join(src, ent.name);
      const d = join(dst, ent.name);
      if (ent.isDirectory()) copyWalk(s, d);
      else {
        copyFileSync(s, d);
        copied += 1;
      }
    }
  };
  copyWalk(distDir, pub);
  console.log(`  [sync] dist → src/${cfg.flavor}/assets/public（${copied} 个文件）`);

  // capacitor.config.json 必须**每 flavor 一份**（appId / appName 不同）；
  // 放在 flavor 目录里，Gradle 合并时会覆盖 main 中的同名文件。
  writeFileSync(
    join(flavorDir, 'capacitor.config.json'),
    `${JSON.stringify(
      {
        appId: cfg.appId,
        appName: cfg.appName,
        webDir: 'dist',
        android: { allowMixedContent: false },
      },
      null,
      2,
    )}\n`,
  );
  console.log(`  [sync] 写入 src/${cfg.flavor}/assets/capacitor.config.json（appId=${cfg.appId}）`);
}

/**
 * 构建单个 flavor，并把产物**复制进归档目录**（不覆盖任何既有文件）。
 *
 * @param destDir 归档目录（`release/<buildId>/`），由 `main()` 创建并保证唯一
 * @param buildId 构建号，用于产物文件名
 */
async function buildVariant(variant, destDir, buildId) {
  const cfg = VARIANTS[variant];
  console.log(`\n\x1b[1m\x1b[35m══════ 构建 ${variant}（${cfg.appName}）══════\x1b[0m`);

  // 1) web 产物：注入构建期开关（这一步是"两个包真正不同"的根源）
  await run('npm', ['run', 'build'], { env: { VITE_BUILTIN_XINRAN: cfg.env } });

  // 2) ★ 启动兼容性检查（详见函数头部注释）—— 失败即拒绝打包
  console.log('\n\x1b[1m\x1b[35m══════ 启动兼容性检查 ══════\x1b[0m');
  await run(process.execPath, [join(ROOT, 'scripts', 'qa', 'check-boot-compat.mjs')], { shell: false });
  console.log('\x1b[32m✓ 启动兼容性检查通过\x1b[0m');

  // 3) 同步到该 flavor 专属的原生 assets（自实现，理由见 syncWebAssets 注释）
  syncWebAssets(cfg);

  // 4) 编译
  const gradlew = process.platform === 'win32' ? 'gradlew.bat' : './gradlew';
  await run(gradlew, [cfg.gradleTask, '--no-daemon'], {
    cwd: ANDROID,
    env: JAVA_HOME ? { JAVA_HOME } : {},
  });

  // 5) 收产物 + 校验版本
  const apk = findApk(variant);
  if (!apk) throw new Error(`${variant}: 没找到 APK 产物`);

  const dest = join(destDir, cfg.apkName.replace('{buildId}', buildId));
  // ★ 碰撞守卫：归档目录里**绝不允许**有同名文件被覆盖
  //   （buildId 精确到秒，正常不会撞；真撞上说明有并发或时钟异常，必须让人看见而不是静默覆盖）
  if (existsSync(dest)) {
    throw new Error(
      `产物已存在，拒绝覆盖：${dest}\n` +
        `  ⇒ 这是用户明确要求的"不覆盖上一版本"。若确需重打，请等一秒后重试（构建号含秒级时间戳）。`,
    );
  }
  copyFileSync(apk, dest);

  const size = (statSync(dest).size / 1024 / 1024).toFixed(1);
  console.log(`\n\x1b[32m✓ ${variant} → ${dest}（${size} MB）\x1b[0m`);

  const { problems, notes, checked, found, hardening } = await verifyApk(dest, variant);
  console.log(`  版本校验：扫了 ${checked} 个 JS chunk，命中特征 [${found.join(', ') || '无'}]`);
  for (const n of notes) console.log(`    · ${n}`);
  if (hardening) {
    console.log(
      `  加固指标：dex ${hardening.dexKB ?? '?'} KB（${hardening.dexCount ?? '?'} 个）｜` +
        `\`com/getcapacitor\` 字符串 ${hardening.capacitorStrings ?? '?'} 次｜` +
        `sourcemap ${hardening.sourcemapCount ?? '?'} 个｜` +
        `签名 ${typeof hardening.signature === 'object' ? JSON.stringify(hardening.signature) : (hardening.signature ?? '?')}`,
    );
  }

  if (problems.length > 0) {
    console.error(`\x1b[31m  ✗ 版本校验失败：\x1b[0m`);
    for (const p of problems) console.error(`     - ${p}`);
    throw new Error(`${variant} 版本校验未通过`);
  }
  console.log('  \x1b[32m✓ 版本特征、清单与加固均正确\x1b[0m');
  return {
    flavor: variant,
    apkId: cfg.appId,
    appName: cfg.appName,
    file: cfg.apkName.replace('{buildId}', buildId),
    bytes: statSync(dest).size,
    sha256: sha256File(dest),
    path: dest,
    jsChunks: checked,
    markers: found,
    // ★ 加固指标进归档记录：**跨版本可对比**（下次想确认"加固还在不在"，
    //   看 MANIFEST 里这一段的数字就行，不必重新反编译一遍）。
    hardening: hardening ?? null,
  };
}

/* ══════════════════════════════════════════════════════════════════════════
 * 归档查询与校验
 * ══════════════════════════════════════════════════════════════════════════ */

/**
 * 列出 `release/` 下所有构建号，按**版本先后**升序。
 *
 * ★ 排序必须按**数值**而不是字典序（2026-10-04 改为 v1/v2 命名后新增的坑）：
 *   `['v1','v10','v2'].sort()` 得到的是 `v1, v10, v2` ——
 *   **字典序下 `v10` 会被当成比 `v2` 更早**，于是"最新构建"会取错。
 *   这个 bug 在只有个位数版本时不会暴露，第 10 个版本才发作 —— 属于典型的
 *   "埋很久才响"的雷，所以在这里一次性处理掉，不等它出事。
 */
function listBuilds() {
  if (!existsSync(RELEASE_DIR)) return [];
  return readdirSync(RELEASE_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory() && e.name.startsWith('v'))
    .map((e) => e.name)
    .sort((a, b) => {
      const na = /^v(\d+)$/.exec(a);
      const nb = /^v(\d+)$/.exec(b);
      if (na && nb) return Number(na[1]) - Number(nb[1]);
      // 编号版本排在历史命名版本之后（编号规则是最新采用的）
      if (na) return 1;
      if (nb) return -1;
      return a.localeCompare(b);
    });
}

/** 取最新构建号；`release/` 为空时返回 null */
function latestBuild() {
  const all = listBuilds();
  return all.length > 0 ? all[all.length - 1] : null;
}

/** 读某个构建的 MANIFEST.json；不存在/损坏返回 null */
function readManifest(buildId) {
  const p = join(RELEASE_DIR, buildId, 'MANIFEST.json');
  if (!existsSync(p)) return null;
  try {
    return JSON.parse(readFileSync(p, 'utf8'));
  } catch {
    return null;
  }
}

/* ══════════════════════════════════════════════════════════════════════════
 * 主流程
 * ══════════════════════════════════════════════════════════════════════════ */

/**
 * 主流程。
 *
 *   node scripts/build-apk.mjs                 两个版本都打，归档到 release/<buildId>/
 *   node scripts/build-apk.mjs builtin         只打内置版（仍归入同一个新目录）
 *   node scripts/build-apk.mjs --list          列出历史构建（含对应关系）
 *   node scripts/build-apk.mjs --verify        校验**最新**构建（APK + 源码 + 对应关系）
 *   node scripts/build-apk.mjs --verify <id>   校验指定构建
 *
 * ★ 与旧版的根本差别：**产物不再覆盖**。旧版固定写 `apk-out/ai爱-内置欣然-v1.0.apk`，
 *   每打一次就把上一版顶掉（历史不可追）。现在一版一个目录，只增不改。
 */
async function main() {
  const arg = process.argv[2];

  /* ── 列出历史 ── */
  if (arg === '--list') {
    const all = listBuilds();
    if (all.length === 0) {
      console.log('\nrelease/ 下还没有任何构建。跑一次 `node scripts/build-apk.mjs` 即会创建。\n');
      return;
    }
    console.log(`\n═══ 历史构建（${all.length} 个，旧的在上）═══\n`);
    for (const id of all) {
      const mf = readManifest(id);
      if (!mf) {
        console.log(`  ${id}  ⚠️ 无 MANIFEST.json（无法核对对应关系）`);
        continue;
      }
      const apks = (mf.variants ?? []).map((v) => `${v.file} (${(v.bytes / 1024 / 1024).toFixed(1)}MB)`);
      console.log(`  ${id}`);
      console.log(`    构建时间 ${mf.builtAt}｜git ${String(mf.git?.head ?? '').slice(0, 12)}｜未提交 ${mf.git?.dirty ?? '?'} 项`);
      for (const a of apks) console.log(`    APK   ${a}`);
      console.log(`    源码  ${mf.sourceBackup?.file ?? '(缺)'}`);
    }
    console.log(`\n索引：${join(RELEASE_DIR, 'INDEX.md')}\n`);
    return;
  }

  /* ── 校验（含**版本对应关系**）── */
  if (arg === '--verify') {
    const want = process.argv[3] ?? latestBuild();
    if (!want) {
      console.error('release/ 下没有任何构建可校验。先跑一次构建。');
      process.exit(2);
    }
    const buildDir = join(RELEASE_DIR, want);
    if (!existsSync(buildDir)) {
      console.error(`找不到构建：${buildDir}`);
      process.exit(2);
    }
    const mf = readManifest(want);
    console.log(`\n═══ 校验构建 ${want} ═══\n目录：${buildDir}\n`);

    let bad = 0;

    // ① 对应关系的前提：MANIFEST 必须存在
    if (!mf) {
      console.error('  ✗ 缺少 MANIFEST.json —— 无法核对"APK ↔ 源码"对应关系');
      process.exit(1);
    }

    // ② APK：既校验"包本身正确"，也校验"与 MANIFEST 记录的哈希一致"（防归档后被换过）
    for (const v of mf.variants ?? []) {
      const p = join(buildDir, v.file);
      console.log(`\n\x1b[1m${v.flavor}\x1b[0m ← ${v.file}`);
      if (!existsSync(p)) {
        console.error('  ✗ 文件不存在');
        bad += 1;
        continue;
      }
      const actual = sha256File(p);
      if (actual !== v.sha256) {
        console.error(`  ✗ 哈希不符（归档后文件被改动过？）`);
        console.error(`     MANIFEST: ${v.sha256}`);
        console.error(`     实际    : ${actual}`);
        bad += 1;
      } else {
        console.log(`  ✓ 哈希与 MANIFEST 一致（${actual.slice(0, 16)}…）`);
      }
      const { problems, notes, checked, found, hardening } = await verifyApk(p, v.flavor);
      console.log(`  JS chunk ${checked} 个，命中内置特征 [${found.join(', ') || '无'}]`);
      for (const n of notes) console.log(`    · ${n}`);

      /* ★ 加固指标：**现场重测**并与 MANIFEST 记录比对。
       *   为什么要比对而不是只打印现场值：
       *     归档的意义是"这一版当时是什么样"。若归档后被换了包，
       *     哈希那一条已经能发现；但若有人**改过 build.gradle 又重打包、
       *     忘了改版本号**，那就是另一回事了 —— 现场值会与记录不符，
       *     这里把它显式指出来。 */
      if (hardening) {
        console.log(
          `    加固现场值：dex ${hardening.dexKB} KB｜\`com/getcapacitor\` ${hardening.capacitorStrings} 次｜` +
            `sourcemap ${hardening.sourcemapCount} 个｜allowBackup ${hardening.allowBackup}｜debuggable ${hardening.debuggable}`,
        );
        const rec = v.hardening;
        if (rec && typeof rec === 'object') {
          if (rec.dexKB !== hardening.dexKB) {
            console.log(
              `    \x1b[33m⚠️ dex 体积与归档记录不符：记录 ${rec.dexKB} KB vs 现场 ${hardening.dexKB} KB\x1b[0m`,
            );
          }
          if (rec.capacitorStrings !== hardening.capacitorStrings) {
            console.log(
              `    \x1b[33m⚠️ 混淆程度与归档记录不符：记录 ${rec.capacitorStrings} 次 vs 现场 ${hardening.capacitorStrings} 次\x1b[0m`,
            );
          }
        } else {
          console.log('    \x1b[90m（该版本早于加固，MANIFEST 里没有 hardening 段）\x1b[0m');
        }
      }
      if (problems.length > 0) {
        console.error('  \x1b[31m✗ 包校验失败\x1b[0m');
        for (const pr of problems) console.error(`     - ${pr}`);
        bad += 1;
      } else {
        console.log('  \x1b[32m✓ 包校验通过\x1b[0m');
      }
    }

    // ③ 源码备份：存在 + 哈希一致 + 内部自带清单
    const sb = mf.sourceBackup;
    console.log(`\n\x1b[1m源码备份\x1b[0m ← ${sb?.file ?? '(MANIFEST 未记录)'}`);
    if (!sb?.file) {
      console.error('  ✗ MANIFEST 里没有源码备份记录 ⇒ 违背"每个 APK 必须配对源码备份"');
      bad += 1;
    } else {
      const sp = join(buildDir, sb.file);
      if (!existsSync(sp)) {
        console.error('  ✗ 源码备份文件不存在 ⇒ 这一版**不可追溯**');
        bad += 1;
      } else {
        const actual = sha256File(sp);
        if (actual !== sb.sha256) {
          console.error(`  ✗ 哈希不符：MANIFEST ${sb.sha256} vs 实际 ${actual}`);
          bad += 1;
        } else {
          console.log(`  ✓ 哈希与 MANIFEST 一致（${actual.slice(0, 16)}…）`);
        }
        console.log(`  ✓ 大小 ${(sb.bytes / 1024 / 1024).toFixed(1)} MB`);
      }
    }

    // ④ 独立复核文件（不依赖本脚本也能验）
    const sumsPath = join(buildDir, 'SHA256SUMS.txt');
    console.log(`\n\x1b[1mSHA256SUMS.txt\x1b[0m`);
    if (!existsSync(sumsPath)) {
      console.error('  ✗ 缺失（`sha256sum -c` 无法独立复核）');
      bad += 1;
    } else {
      console.log(`  ✓ 存在（可直接 \`cd ${buildDir} && sha256sum -c SHA256SUMS.txt\` 复核）`);
    }

    // ⑤ ★ 边界提醒：本次校验**证明了什么、又没证明什么**。
    //   不加这一段的话，遗留目录（correspondence = 不可核实）也会打印"全部通过 ✓"，
    //   而"通过"指的是"哈希一致 + 包特征正确"，**不是**"源码与 APK 配套"。
    //   这句话必须由工具自己说出来 —— 不能指望读日志的人记得去翻 docs。
    const 不可核实 = typeof mf.correspondence === 'string' && mf.correspondence.includes('不可核实');
    console.log('\n\x1b[1m本次校验的边界\x1b[0m');
    console.log('  ✓ 已证明：各文件内容与 MANIFEST/SHA256SUMS 记录一致（未被改动过）');
    console.log('  ✓ 已证明：两个 APK 的包特征正确（内置/不内置没有打反）');
    if (不可核实) {
      console.log('  \x1b[33m✗ 未证明：源码备份与 APK 的对应关系 —— 本目录标记为「不可核实」\x1b[0m');
      console.log(`     MANIFEST.correspondence: ${mf.correspondence}`);
      if (existsSync(join(buildDir, 'LEGACY-NOTE.md'))) {
        console.log(`     实情见：${join(buildDir, 'LEGACY-NOTE.md')}`);
      }
    } else {
      console.log('  ✓ 对应关系：APK 与源码备份同处本目录（由同一次构建产出）');
    }
    console.log('  \x1b[90m✗ 恒未证明：APK 在真机上装得上、跑得对（需真机安装测试，属另一条验收线）\x1b[0m');

    console.log(`\n═══ ${bad === 0 ? '全部通过 ✓' : `${bad} 项失败`} ═══\n`);
    process.exit(bad === 0 ? 0 : 1);
  }

  /* ── 构建 ── */
  const targets = arg ? [arg] : Object.keys(VARIANTS);
  for (const t of targets) {
    if (!VARIANTS[t]) {
      console.error(`未知版本：${t}（可选 ${Object.keys(VARIANTS).join(' / ')}）`);
      process.exit(2);
    }
  }

  // 前置自检
  if (!existsSync(join(ANDROID, 'local.properties'))) {
    console.warn('⚠️  没有 android/local.properties —— AGP 可能找不到 SDK（要靠 ANDROID_HOME 环境变量）');
  }
  if (!existsSync(join(ANDROID, 'keystore.properties'))) {
    console.warn('⚠️  没有 android/keystore.properties —— release 包会是 unsigned，**装不上**');
  }
  if (JAVA_HOME) {
    console.log(`JDK：${JAVA_HOME}`);
  } else {
    console.warn('⚠️  没找到 JDK —— Gradle 会失败。装一个 JDK 21，或设 JAVA_HOME 后重试');
  }

  /**
   * ★★ 启动兼容性检查 —— **失败即拒绝打包**（2026-10-04 加，防复发）。
   *
   * 为什么把这一步放进打包流程，而不是"需要时手动跑"：
   *   2026-10-04 出过一次 P0 —— 交付给用户的 APK **打开是纯空白屏**。
   *   根因是启动路径上用了 `structuredClone`（WebView 98+ 才有），
   *   用户机器版本更低 ⇒ 入口模块求值失败 ⇒ React 从未挂载。
   *   详见 `docs/10-真机白屏故障诊断报告.md`。
   *
   *   而**当时所有的检查都通过了**：能力表 141 项、截图比对、APK 特征校验 ——
   *   没有一项在问"这个包在老设备上能启动吗"。
   *   ⇒ 一个只存在于文档里的检查等于不存在，必须让**构建流程本身**拦住它。
   *
   * ★ 为什么放在这里（`npm run build` 之后、`syncWebAssets` 之前）：
   *   此刻 `dist/` 就是**即将被打进这个 flavor 的那份产物**，
   *   检查的正是最终要交付的东西，而不是"上次构建的残留"。
   *   同时把失败拦在 gradle 之前 —— gradle 一轮 30s+，没必要等打完再发现。
   *
   * ★ 检查内容（细节见 `scripts/qa/check-boot-compat.mjs`）：
   *   ① 入口 chunk 不得含高危运行时 API（structuredClone / Object.hasOwn）；
   *   ② 入口 chunk 不得含新语法（`?.` / `??` —— 语法解析失败会让整个 bundle **静默**失效）；
   *   ③ `index.html` 必须内含 ES5 兜底脚本、静态启动页、错误面板，且兜底在 module script 之前。
   *
   * ★ 为什么只做**静态**检查、不把动态的（`--legacy` 模拟）也放进来：
   *   动态那条要起浏览器，会让打包多花十几秒且依赖环境。
   *   静态检查已能覆盖真实回归（例如将来有人手顺把 `deepClone` 改回 `structuredClone`，
   *   或误删 index.html 里的兜底段）。动态那条留在 QA 里按需跑。
   */
  console.log('\n\x1b[1m\x1b[35m══════ 启动兼容性检查 ══════\x1b[0m');
  await run(process.execPath, [join(ROOT, 'scripts', 'qa', 'check-boot-compat.mjs')], { shell: false });
  console.log('\x1b[32m✓ 启动兼容性检查通过\x1b[0m');

  // ★ 构建号与归档目录：**在任何编译动作之前**就确定并占位，
  //   这样"这次构建对应哪个目录"从头到尾唯一，中途失败也不会让后来的构建混进旧目录。
  //   `version` / `versionCode` 仍读出来记进 MANIFEST（用户能在系统"应用信息"里看到），
  //   但**不再参与构建号** —— 构建号现在是纯递增的 `v1`/`v2`/…（见 `makeBuildId`）。
  const version = readVersion();
  const versionCode = readVersionCode();
  const buildId = process.env.BUILD_ID_OVERRIDE || makeBuildId();
  const buildDir = join(RELEASE_DIR, buildId);

  if (existsSync(buildDir)) {
    throw new Error(
      `归档目录已存在，拒绝覆盖：${buildDir}\n` +
        `  ⇒ 用户明确要求"不覆盖、不替换、不删除"上一版本。请等一秒后重试。`,
    );
  }
  mkdirSync(buildDir, { recursive: true });
  console.log(`\n构建号：\x1b[1m${buildId}\x1b[0m`);
  console.log(`归档目录：${buildDir}`);

  const built = [];
  for (const t of targets) built.push(await buildVariant(t, buildDir, buildId));

  // ★ 源码备份：**必须**与 APK 同目录产出，这是"一一对应"的实现方式
  console.log(`\n\x1b[1m\x1b[35m══════ 备份该版本源码 ══════\x1b[0m`);
  await backupSourceInto(buildDir, buildId);

  // 找到刚生成的源码 zip（backup-source.py 会拼上日期后缀，故这里按前缀匹配而不是猜全名）
  const prefix = `ai爱-源码-${buildId}`;
  const zipName = readdirSync(buildDir).find((f) => f.startsWith(prefix) && f.endsWith('.zip'));
  if (!zipName) {
    throw new Error(
      `源码备份似乎没产出（找不到 ${prefix}*.zip）⇒ 违背"每个 APK 必须配对源码备份"。`,
    );
  }
  const zipPath = join(buildDir, zipName);

  const info = {
    buildId,
    builtAt: new Date().toISOString(),
    appName: 'ai爱',
    versionName: version,
    versionCode,
    git: await gitInfo(),
    variants: built.map((b) => ({
      flavor: b.flavor,
      appId: b.apkId,
      appName: b.appName,
      file: b.file,
      bytes: b.bytes,
      sha256: b.sha256,
      jsChunks: b.jsChunks,
      seedMarkers: b.markers,
      verifiedAtBuild: true,
      // ★ 加固指标（2026-10-04 起）。跨版本对比用；缺字段说明是加固前的旧版本。
      hardening: b.hardening,
    })),
    sourceBackup: {
      file: zipName,
      bytes: statSync(zipPath).size,
      sha256: sha256File(zipPath),
      producedBy: 'scripts/backup-source.py',
      note: '与同目录 APK 由同一次构建产出 ⇒ 一一对应；内部含 BACKUP-MANIFEST.txt 自述',
    },
    correspondence: '本目录内的 APK 与该源码备份由同一次构建产生，一一对应、可追溯',
  };

  const mfPath = writeManifest(buildDir, info);
  const sums = writeSums(buildDir, [
    ...info.variants.map((v) => ({ file: v.file, sha256: v.sha256 })),
    { file: info.sourceBackup.file, sha256: info.sourceBackup.sha256 },
  ]);
  const idxPath = appendIndex(info);

  console.log('\n\x1b[1m\x1b[32m══════ 完成 ══════\x1b[0m');
  console.log(`  构建号  ${buildId}`);
  for (const b of built) console.log(`  APK     ${b.file}（${(b.bytes / 1024 / 1024).toFixed(1)} MB）`);
  console.log(`  源码    ${zipName}（${(info.sourceBackup.bytes / 1024 / 1024).toFixed(1)} MB）`);
  console.log(`  清单    ${mfPath}`);
  console.log(`  校验和  ${sums}`);
  console.log(`  索引    ${idxPath}（只追加）`);
  console.log(`\n  复验：node scripts/build-apk.mjs --verify ${buildId}`);
  console.log(`  列表：node scripts/build-apk.mjs --list\n`);
}

main().catch((e) => {
  console.error(`\n\x1b[31m打包失败：${e.message}\x1b[0m`);
  process.exit(1);
});
